MobilityData/gtfs-validator

adapter/repository/in-memory-simple/src/main/resources/gtfs_spec.asciipb

**Summary:**
This PR adapts the schema file to represent the current version of the GTFS specification.

Changes to asciipb file

---

adapter/parser/src/main/java/org/mobilitydata/gtfsvalidator/parser/GtfsEntityParser.java
adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/FromFileRawEntityProvider.java
adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsSpecRepository.java
adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryRawFileRepository.java
adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryValidationResultRepository.java
adapter/validator/src/main/java/org/mobilitydata/gtfsvalidator/validator/GtfsTypeValidator.java
config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/ParsedEntity.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/RawEntity.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/RawFileInfo.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/CleanOrCreatePath.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/DownloadArchiveFromNetwork.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ParseSingleRowForFile.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/UnzipInputArchive.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAllRequiredFilePresence.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAllRowLengthForFile.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateGtfsTypes.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateHeadersForFile.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/GtfsSpecRepository.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/RawFileRepository.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/ValidationResultRepository.java

**Summary:**
This PR will add javadoc comments in order to clarify the use of the code developed at this stage of the project. 
Related issue #40 

Implement #40 - Add javadoc comments

---

README.md
adapter/exporter/build.gradle
adapter/parser/build.gradle
adapter/protos/build.gradle
adapter/repository/in-memory-simple/build.gradle
adapter/validator/build.gradle
application/cli-app/build.gradle
application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java
config/build.gradle
domain/build.gradle
usecase/build.gradle

**Summary:**
This PR for final changes before release

Preparing release v1.1.0

---

README.md

**Summary:**
Adds additional useful info the README, including:
* Java version requirement and link
* Where to download the JAR file for releases
* Improved description of usage
* Basic description and links to architecture modules
* Fix a few links (e.g., to the schema)
Some info is from @fabrice-v's post today in Slack:
https://mobilitydata-io.slack.com/archives/C0J4TJY8L/p1585577121009500
@fabrice-v @lionel-nj Let me know if I missed or need to fix anything
README includes additional info to help people download, setup, and execute the validator

Update README with additional setup and execution info

---

adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryExecParamRepository.java
config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/DownloadArchiveFromNetwork.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ExportResultAsFile.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/GenerateExclusionFilenameList.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/GenerateFilenameListToProcess.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/LogExecutionInfo.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/PrintHelp.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/UnzipInputArchive.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateRouteColorAndTextContrast.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateRouteDescriptionAndNameAreDifferent.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateRouteLongNameDoesNotContainOrEqualShortName.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateRouteShortNameLength.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateRouteTypeIsInTypeOptions.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateShortAndLongNameForRoutePresence.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ExportResultAsFileTest.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/GenerateExclusionFilenameListTest.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/GenerateFilenameListToProcessTest.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateRouteColorAndTextContrastTest.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateRouteDescriptionAndNameAreDifferentTest.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateRouteLongNameDoesNotContainOrEqualShortNameTest.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateRouteShortNameLengthTest.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateRouteTypeIsInTypeOptionsTest.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateShortAndLongNameForRoutePresenceTest.java

**Summary:**
This PR provides support to improve the output log:
- legibility has been improved by adding a new line after each message
- new messages after logged regarding the execution of file specific use cases.
Information is logged and more legible.

Implement #252 -- Improve information logging

---

application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java

**Summary:**
This PR provides support to display the duration of the validation process in `hh:mm:ss` format.
Duration should be logged with `hh:mm:ss` format. 

Implement #282 - Change time format

---

adapter/parser/src/main/java/org/mobilitydata/gtfsvalidator/parser/GtfsEntityParser.java
adapter/parser/src/test/java/org/mobilitydata/gtfsvalidator/parser/GtfsEntityParserTest.java
adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepository.java
adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepositoryTest.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/Calendar.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/FeedInfo.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/calendardates/CalendarDate.java
domain/src/test/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/CalendarTest.java
domain/src/test/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/FeedInfoTest.java
domain/src/test/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/calendardates/CalendarDateTest.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ProcessParsedCalendar.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ProcessParsedCalendarDate.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ProcessParsedFeedInfo.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/GtfsDataRepository.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ProcessParsedCalendarDateTest.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ProcessParsedCalendarTest.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ProcessParsedFeedInfoTest.java

**Summary:**
This PR changes the use of library `LocalDateTime` for `LocalDate` 
No visible change. 

Fix #276 -- Use LocalDate instead of LocalDateTime

---

ADDING_NEW_RULES.md

**Summary:**
This PR adds documentation regarding the required steps to add a new validation rule to the validator. It is heavily inspired by https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/ADDING_NEW_RULES.md

Add documentation on how to add a rule

---

.github/workflows/gradle.yml
adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/NoticeMemoryConsumptionTest.java

**Summary:**
Latest changes to workflow led to unit testing to be skipped

Adding a step to run tests

---

.github/ISSUE_TEMPLATE/bug_report.md

**Summary:**
This adds a **gtfs-validator** version field to the issue template.

Ask for gtfs-validator in bug reports

---

RULES.md
adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporter.java
adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporter.java
adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporterTest.java
adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporterTest.java
adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepository.java
adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepositoryTest.java
application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java
config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/Agency.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/NoticeExporter.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/ErrorNotice.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/InconsistentAgencyTimezoneNotice.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/InvalidAgencyIdNotice.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/MissingAgencyIdNotice.java
domain/src/test/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/AgencyTest.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAgenciesHaveSameAgencyTimezone.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAgencyIdRequirement.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAgencyTimezoneAreInAccord.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/GtfsDataRepository.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAgenciesHaveSameAgencyTimezoneTest.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAgencyIdRequirementTest.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAgencyTimezoneAreInAccordTest.java

**Summary:**
This PR provides support to validate rules related to file `agency.txt`. 
This rule has been implemented in 5b05fd9c0aac8a4037ca4ff2b4adbae4d9cf06f6

Use cases classes -- Agency related use cases

---

.github/workflows/gradle.yml
README.md

**Summary:**
This PR modifies GitHub workflow to have artifacts archived separately instead of all at once. 

Separate artifacts

---

domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/pathways/Pathway.java
domain/src/test/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/pathways/PathwayTest.java

**Summary:**
Fixing incorrect notices being generated on negative `stair_count` in `pathways.txt`
close #322 

Fix #322 - change <= to == in PathwayBuilder

---

.github/workflows/gradle.yml
adapter/exporter/build.gradle
adapter/parser/build.gradle
adapter/protos/build.gradle
adapter/tree/build.gradle
adapter/utils/build.gradle
adapter/validator/build.gradle
application/cli-app/build.gradle
config/build.gradle
domain/build.gradle
usecase/build.gradle

**Summary:**
This PR contains changes for v1.2.1 as well as prepping for next release

v1.2.1 Release

---

adapter/utils/build.gradle
adapter/utils/src/main/java/org/mobilitydata/gtfsvalidator/geoutils/GeospatialUtilsImpl.java
adapter/utils/src/main/java/org/mobilitydata/gtfsvalidator/timeutils/TimeUtilsImpl.java
adapter/utils/src/test/java/org/mobilitydata/gtfsvalidator/geoutils/GeospatialUtilsImplTest.java
adapter/utils/src/test/java/org/mobilitydata/gtfsvalidator/timeutils/TimeUtilsImplTest.java
config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/utils/GeospatialUtils.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/utils/TimeUtils.java

**Summary:**
This PR adds a geospatial utilities class to the project in preparation for #137 and #155 . 
Third party libraries are encapsulated through the use of an interface.
It's modeled after what was done for time related utilities and includes name changes for consistency.
@barbeau I split this off in its own PR so it could be reviewed and merged independently of progress made on the two mentioned issues and provide a place in which to put any methods required by 137

Geospatial utility class

---

.github/workflows/gradle.yml
RULES.md
adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporter.java
adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporter.java
adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporterTest.java
adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporterTest.java
adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/NoticeMemoryConsumptionTest.java
config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/NoticeExporter.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/ErrorNotice.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/Notice.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/DecreasingShapeDistanceNotice.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateShapeIncreasingDistance.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/usecasevalidator/ShapeBasedCrossValidator.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateShapeIncreasingDistanceTest.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/usecasevalidator/ShapeBasedCrossValidatorTest.java

**Summary:**
This PR provides support to verify `shape_dist_traveled` stricly increase along a shape.

Implement #358 - Verify increasing shape_dist_traveled along a shape

---

.github/workflows/gradle.yml
adapter/exporter/build.gradle
adapter/parser/build.gradle
adapter/protos/build.gradle
adapter/tree/build.gradle
adapter/utils/build.gradle
adapter/validator/build.gradle
application/cli-app/build.gradle
config/build.gradle
domain/build.gradle
usecase/build.gradle

**Summary:**
Release PR for version 1.2.2

Release v1.2.2

---

RULES.md

**Summary:**
closes #368
This PR update RULES.md so that it contains definitions for all supported rules

RULES - add definitions for all supported rules

---

.github/workflows/endtoend.yml

closes #406  
**Summary:**
Add a worflow to run the validator on multiple datasets when code is merged on master
On future merge to master, the validator should run on both MBTA and STM datasets

End to end testing workflow

---

.circleci/config.yml
.github/workflows/endtoend.yml
.github/workflows/gradle.yml
README.md
RELEASE.md
application/cli-app/build.gradle

**Summary:**
closes #416 
The content of this PR covers
- adding circle CI workflows to PR checks
Circle CI checks running on this PR
A public page showing equivalent processing as the GitHub Action
https://app.circleci.com/pipelines/github/MobilityData/gtfs-validator
As well as a way to retrieve artifacts
- cli jar (under `package`)
- java tests report (under `test`)
- javadoc (under `doc`)

Implement second CI solution as backup

---

.github/workflows/endtoend.yml
adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepository.java
adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepositoryTest.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/DownloadArchiveFromNetwork.java

**Summary:**
This PR provides support to handle URL redirections.
gtfs-validator should be able to download `.zip` files when content to download has been moved.

Fix 398 - Implement solution to handle URL redirections

---

README.md
adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporter.java
adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepository.java
adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryValidationResultRepository.java
adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepositoryTest.java
adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/InMemoryValidationResultRepositoryTest.java
config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ExportResultAsFile.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/GtfsDataRepository.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/ValidationResultRepository.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ExportResultAsFileTest.java

**Summary:**
This PR provides support to rename the validation report as the `feed_info.feed_publisher_name` + `__` + timestamp + file extension (`.json` or `.pb`). All whitespace characters are replaced by `_` before using the resulting path.
**1. Validation report as `.json`:**
Validation reports should no longer be named `results.json`. Instead the name of said file should be `feed_info.feed_publisher_name` + `__` `timestamp`(at the time of validation in `America/Montreal` timezone) +`.json`.
If `feed_info.txt` is not provided then the name of the validation report is limited to the timestamp at the moment of validation in `America/Montreal` timezone.
**Sample filename:** after validating [MBTA's GTFS archive](https://cdn.mbta.com/MBTA_GTFS.zip) on 2020-10-20 at …

Implement #435 - Rename validation report

---

README.md

closes #372  
**Summary:**
This PR adds information to `README.md`:
- additional information regading web app developement mode
- fix typos
Code execution should remain the same. Additional information should be displayed in said file.

Implement #372 - Update readme

---

.github/workflows/test_pack_doc.yml

**Summary:**
Small typo fix for one of the test task names
Show the correct name in GitHub Actions UI when run

docs: Fix typo in workflow comment

---

.github/workflows/end_to_end.yml
README.md
adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporter.java
adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporter.java
adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporterTest.java
adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporterTest.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/NoticeExporter.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/InfoNotice.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/Notice.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/info/UnsupportedGtfsStructureNotice.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateNoOverlappingStopTimeInTripBlock.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateNoOverlappingStopTimeInTripBlockTest.java

closes #458 
**Summary:**
This PR provides support to gracefully handle NPE thrown in #397 as a first step.
No NPE. An info notice should be generated and added to the `ValidationResultRepository`.

Gracefully handle NPE thrown in #397

---

adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporter.java
adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporter.java
adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporterTest.java
adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporterTest.java
adapter/parser/src/main/java/org/mobilitydata/gtfsvalidator/parser/GtfsEntityParser.java
adapter/parser/src/test/java/org/mobilitydata/gtfsvalidator/parser/GtfsEntityParserTest.java
application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java
domain/build.gradle
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/RawEntity.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/calendardates/CalendarDate.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/NoticeExporter.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/WarningNotice.java
domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/warning/MalformedCsvRowNotice.java
domain/src/test/java/org/mobilitydata/gtfsvalidator/domain/entity/RawEntityTest.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ParseSingleRowForFile.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAllRowLengthForFile.java
usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/MalformedCsvRowException.java
usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAllRowLengthForFileTest.java

closes #401 
**Summary:**
This PR provides support to prevent the erroneous generation of `MissingRequiredValueNotice` when a GTFS file contains blank lines.
`MalformedCsvRowNotice` should be generated and added to the validation result repo if:

False positive on missing calendar_date field

---

.github/workflows/end_to_end.yml

closes #473 
**Summary:**
This PR provides support to explicit options long name instead of using options short name in end to end workflow.
No change.
- ~[] Format the title like "Fix #<issue_number> - <short description of fix and changes>" (for example - "Fix #1111 - Check for null value before using field")~

Improve end to end workflow clarity

---

.github/PULL_REQUEST_TEMPLATE.md

**Summary:**
This PR updates the PR template to reflect the latest enforcement of conventional PR titles. 
No code change: PR template should include reference to conventional commit types.

docs: update PR template to match conventional commit requirements

---

.github/workflows/end_to_end.yml

**Summary:**
This PR adjust the `end_to_end.yml` file to execute the validator on MBTA's  dataset.
No exception.

ci: Fix MBTA run command

---

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java

Non-exhaustive switch is an error at Google.

fix: Add a default branch to case

---

core/build.gradle
core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsInput.java

Use org.apache.httpcomponents:httpclient:4.5.2 instead of org.apache.httpcomponents.client5:httpclient5:5.0.3
Switch to the library version supported by Google.

fix: Use org.apache.httpcomponents:httpclient:4.5.2 instead of org.apache.httpcomponents.client5:httpclient5:5.0.3

---

core/build.gradle
core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsInput.java
main/build.gradle
main/src/main/java/org/mobilitydata/gtfsvalidator/cli/CliParametersAnalyzer.java
main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java
main/src/test/java/org/mobilitydata/gtfsvalidator/cli/CliParametersAnalyzerTest.java

Flogger is the recommended logger at Google. Flogger is the result of an attempt to create a unified logging API, suitable for the vast majority of Java projects in Google.

chore: Switch from log4j to Flogger

---

core/build.gradle
core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java
core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainerTest.java

Jackson2 has a terrible security record, with new remote code execution 
vulnerabilities being published once every other month:
https://medium.com/@cowtowncoder/on-jackson-cves-dont-panic-here-is-what-you-need-to-know-54cd0d6e8062

refactor: Switch to Gson library for JSON serialization

---

core/build.gradle
main/build.gradle
processor/build.gradle

chore: Upgrade to Java 11

---

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/Analyser.java
processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/GtfsAnnotationProcessor.java

Google has use cases for that.

feat: Support trivial enum that have a single value

---

.github/workflows/test_pack_doc.yml
processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/Analyser.java
processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/GtfsAnnotationProcessor.java

**Summary:**
This PR applies the GitHub Action https://github.com/axel-op/googlejavaformat-action on all pull requests and pushes to master branch, which will check the format of the code according to https://github.com/google/google-java-format and if it's not formatted correctly with push a commit to automatically format it.
GitHub Action will check the code format, and if it's not formatted will push a commit to format it.
Closes https://github.com/MobilityData/gtfs-validator/issues/615

ci: Automatically format code

---

core/src/test/java/org/mobilitydata/gtfsvalidator/type/GtfsDateTest.java

closes #567 
**Summary:**
This PR provides additional unit tests for `GtfsDate` class
No code change, tests should pass.

test: unit test for GtfsDate

---

core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/CsvRowTest.java

closes #567 
**Summary:**
This PR provides additional unit tests for `CsvRow` class
No code change, tests should pass.

test: unit tests for CsvRow class

---

RULES.md

closes #522 
**Summary:**
This PR adds information to `RULES.md`: documentation about the ryule implemented in #581.
No code change.

docs: add rule documentation (#581)

---

RULES.md
core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NonAsciiOrNonPrintableCharNotice.java
core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java
core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java

closes #529
**Summary:**
This PR implements a new validation rule: no non-ascii character in IDs.
- a notice should be generated if an ID contains non ascii characters

feat: non ascii character in ID

---

RULES.md

closes #714
**Summary:**
This PR updates files `RULES.md` to match the latest development.
No code change.

docs: update rules.md

---

main/src/test/java/org/mobilitydata/gtfsvalidator/cli/ArgumentsTest.java

closes #570 
**Summary:**
This PR provides additional unit test for Arguments class
No code change, tests should pass

test: unit test for Arguments class

---

.github/ISSUE_TEMPLATE/feature_request.md

**Summary:**
This PR adds the "enhancement" label automatically to any "feature request" issues that are opened. This is typically how most repos are configured, as the vast majority of feature requests enhance the project in some way.
If the label doesn't fit for some reason it can be manually removed.
The "enhancement" label automatically to any "feature request" issues that are opened.

docs: Add enhancement label to feature requests

---

.github/PULL_REQUEST_TEMPLATE.md

**Summary:**
This PR updates the pull request template based on more recent protocols.
PR template should be relevant to current issues and workflows and documentation.

docs: Update pull request template

---

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/FeedExpirationDateValidator.java

closes #744
**Summary:**
This PR improves code quality by leveraging `compareTo()` method in rule validator.
Same tests should pass.

refactor: leverage compareTo method

---

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/MissingTripEdgeValidator.java
main/src/test/java/org/mobilitydata/gtfsvalidator/validator/MissingTripEdgeValidatorTest.java

closes #745 
**Summary:**
This PR improves code quality by leveraging `Multimaps`
Same tests should pass.

refactor: Leverage Multimaps 

---

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/MissingTripEdgeValidator.java
main/src/test/java/org/mobilitydata/gtfsvalidator/validator/MissingTripEdgeValidatorTest.java

**Summary:**
This PR: 
- removes a useless statement
- uses `for` loop instead of lambda to improve code clarity
Same tests should pass.

chore: improve MissingTripEdgeValidator code clarity

---

core/build.gradle

**Summary:**
This avoids the error on Windows.
Closes #749
Tests run on Windows without any errors

fix: Set core module compile task encoding to be UTF-8

---

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/GtfsTripServiceIdForeignKeyValidator.java
main/src/test/java/org/mobilitydata/gtfsvalidator/validator/GtfsTripServiceIdForeignKeyValidatorTest.java

trips.txt has service_id column that references calendar.txt or
calendar_dates.txt.

fix: trips.txt is the child table

---

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/EntityImplementationGenerator.java

Avoid null values that can lead to NullPointerException.

fix: Initialize BigDecimal to ZERO

---

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/DuplicateFareRuleZoneIdFieldsValidator.java

**Summary:**
This PR provides changes to improve DuplicateRouteNameValidator
An hash code is used to check for duplicate instead of using String concatenation. 
Same tests should pass.

chore: improve efficiency of DuplicateFareRuleZoneIdFieldsValidator

---

core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java

Only injectable constructors should be used.

feat: Remove support for injectable fields

---

RULES.md
core/src/main/java/org/mobilitydata/gtfsvalidator/notice/DuplicateKeyNotice.java
core/src/main/java/org/mobilitydata/gtfsvalidator/notice/ForeignKeyViolationNotice.java
core/src/main/java/org/mobilitydata/gtfsvalidator/notice/InvalidRowLengthNotice.java
core/src/main/java/org/mobilitydata/gtfsvalidator/notice/MissingRequiredColumnNotice.java
core/src/main/java/org/mobilitydata/gtfsvalidator/notice/MissingRequiredFieldNotice.java
core/src/main/java/org/mobilitydata/gtfsvalidator/notice/MissingRequiredFileNotice.java
core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NumberOutOfRangeNotice.java
core/src/main/java/org/mobilitydata/gtfsvalidator/notice/UnexpectedEnumValueNotice.java
core/src/main/java/org/mobilitydata/gtfsvalidator/notice/ValidationNotice.java
core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java
core/src/main/java/org/mobilitydata/gtfsvalidator/validator/TableHeaderValidator.java
core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainerTest.java
core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java
core/src/test/java/org/mobilitydata/gtfsvalidator/validator/TableHeaderValidatorTest.java
main/src/main/java/org/mobilitydata/gtfsvalidator/validator/AgencyConsistencyValidator.java
main/src/main/java/org/mobilitydata/gtfsvalidator/validator/GtfsTripServiceIdForeignKeyValidator.java
main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TripAgencyIdValidator.java
main/src/test/java/org/mobilitydata/gtfsvalidator/validator/AgencyConsistencyValidatorTest.java
main/src/test/java/org/mobilitydata/gtfsvalidator/validator/GtfsTripServiceIdForeignKeyValidatorTest.java
processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/ForeignKeyValidatorGenerator.java
processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java
processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java

Only child classes of ValidationNotice were affected.

feat: Change Error suffix to Notice

---

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/DuplicateFareRuleZoneIdFieldsValidator.java
main/src/main/java/org/mobilitydata/gtfsvalidator/validator/DuplicateRouteNameValidator.java

farmHashFingerprint64 is better protected against collisions.
Note that we do not use concatenated strings as keys in our hash maps
since they are long, occupy much space and negatively impact
productivity.

perf: Use farmHashFingerprint64 instead of Objects.hash

---

core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsInput.java
core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsUnarchivedInput.java
core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsZipFileInput.java

The set of files is never modified.

fix: Return ImmutableSet from GtfsInput.getFilenames()

---

core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsZipFileInput.java
core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultValidatorProvider.java
core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java
core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorUtil.java
core/src/test/java/org/mobilitydata/gtfsvalidator/validator/DefaultFieldValidatorTest.java
processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java

* it is not recommended to import classes with a generic name like Builder
* add static final modifiers
* avoid raw types
* remove redundant continue
* add missing @Override

fix: Java style fixes

---

core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableContainer.java

Only isMissingFile() method is actually used in
MissingCalendarAndCalendarDateValidator.
If needed, users may call getTableStatus() method. In general,
validators do not need to handle most of the statuses. We may want to
merge INVALID_HEADERS and UNPARSABLE_ROWS to a single status
PARSING_FAILED in a separate PR.

chore: Remove unused methods and document GtfsTableContainer.TableStatus

---

main/src/main/java/org/mobilitydata/gtfsvalidator/cli/CliParametersAnalyzer.java
main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java
main/src/test/java/org/mobilitydata/gtfsvalidator/cli/CliParametersAnalyzerTest.java

**Summary:**
This PR provides support to make `CliParametersAnalyzer` a static class with static method
Same tests should pass. 
- ~[] Linked all relevant issues~

chore: make CliParametersAnalyzer a static class with static method

---

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/LatLonValidatorGenerator.java

S2LatLng.getEarthDistance is deprecated and removed from the new version
of S2 Geometry library that will be used by GTFS Validator.
We simplify the logic that checks that a point is too close to a pole.
```
if (Math.abs(entity.shapePtLat()) >= 89.0) {
noticeContainer.addValidationNotice(
new PointNearPoleNotice(
GtfsShapeTableLoader.FILENAME,
entity.csvRowNumber(),
GtfsShapeTableLoader.SHAPE_PT_LAT_FIELD_NAME,
entity.shapePtLat(),
GtfsShapeTableLoader.SHAPE_PT_LON_FIELD_NAME,
entity.shapePtLon()));
}
```
This new logic is similar to checking that a point lies next to the
origin (0, 0).
```
if (entity.hasShapePtLatLon()) {
if (Math.abs(entity.shapePtLat()) <= 1.0 && Math.abs(entity.shapePtLon()) <= 1.0) {
noticeContainer.addValidationNotice(
new PointNearOriginNotice( …
```

chore: Do not use S2LatLng.getEarthDistance method

---

main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java

Relates to #734 
**Summary:**
This PR provides support to extract intermediate validation methods. The is needed for #933.
Same behavior as before method extraction.

refactor: extract methods from main cli 

---

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayLoopValidator.java
main/src/test/java/org/mobilitydata/gtfsvalidator/validator/PathwayLoopValidatorTest.java

A pathway should not be a loop, i.e. should not start and end in the
same location.

feat: Validate that a pathway is not a loop

---

docs/NOTICES.md
main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopNameValidator.java

relates to #910 
**Summary:**
This PR fixes typos in `StopNameValidator`
No code change: same test should pass

fix: typos in StopNameValidator

---

.github/workflows/end_to_end.yml
.github/workflows/end_to_end_100.yml
.github/workflows/end_to_end_big.yml

closes #1005
**Summary:**
This PR modifies the list of events that trigger the execution of end to end workflows.
These workflows should be triggered on pull request and push events so that hey can be used as smoke tests before merging to master.

ci: execute end_to_end workflows on push and pull request events

---

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ShapeToStopMatchingValidator.java
main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimeTravelSpeedValidator.java
processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java

* move tripFprint method into TripAndStopTimes
* use orElse
* remove Nullable annotation

fix: Address comments in pull #1011

---

main/src/main/java/org/mobilitydata/gtfsvalidator/util/StopUtil.java
main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ParentLocationTypeValidator.java
main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayEndpointTypeValidator.java
main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ShapeToStopMatchingValidator.java
main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimeTravelSpeedValidator.java
main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TranslationFieldAndReferenceValidator.java
processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/EndRangeValidatorGenerator.java
processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/ForeignKeyValidatorGenerator.java

chore: Use Optional.isEmpty() method

---

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopNameValidator.java

closes #1017 
**Summary:**
This PR provides support to update documentation related to `SameNameAndDescriptionForStopNotice`. This notice is a `WARNING` per spec. 
No code change.

docs: update SameNameAndDescriptionForStopNotice documentation

---

docs/USAGE.md

Additional context:
- https://github.com/MobilityData/gtfs-validator/issues/1065

docs: fix typo in USAGE.md

---

.gitignore

**Summary:**
Adds .nosync to .gitignore. Required for mac so that the content of the repo is not synced with iCloud.
Same as before
- [] ~Linked all relevant issues~
- [] ~Include screenshot(s) showing how this pull request works and fixes the issue(s)~

feat: Adds .nosync to .gitignore

---

RULES.md

Closes #1210.
**Summary:**
This PR adds the missing notice in `RULES.md`.
The notice information appears in `RULES.md` and is accurate.
----

Docs: Add point near pole

---

.github/config.yml

**Summary:**
Add a welcome bot for first time issues, first PR opened, and first PR merged. This is part of issue #1175.
The Welcome bot sends a custom message every time a new user opens an issue, a PR or gets a PR merged.

feat: Add config.yml for welcome bot

---

RULES.md

Fixed rule headers for two rules.

docs: fix typo in RULES.md

---

core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsEntityBuilder.java
processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/EntityImplementationGenerator.java

All GTFS entity builders implement this interface.

Introduce GtfsEntityBuilder interface

---

core/src/main/java/org/mobilitydata/gtfsvalidator/table/AnyTableLoader.java

This reverts commit a6cb3ed2556412e4f1ca207b808090419139fd28.

Always invoke single file validators (revert #1300)

---

RULES.md

**Summary:**
Closes #1294. All the other broken links referenced in the issues have been fixed. 

fix: broken link in RULES.md

---

docs/ACCEPTANCE_TESTS.md

**Summary:**
Update our doc after the addition of warning and info to the test. Closes #1349 
The doc matches with the tests

Docs: Update ACCEPTANCE_TESTS.md

---

web/service/README.md
web/service/open-api-spec.json

docs: Update README.md with open api spec

---

docs/USAGE.md

**Summary:**
I noticed the flag in the `USAGES.md` file for generating notices schema was incorrect. 

fix: correct typo for export notices schema flag

---

cli/src/main/java/org/mobilitydata/gtfsvalidator/cli/Arguments.java
cli/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java
cli/src/test/java/org/mobilitydata/gtfsvalidator/cli/ArgumentsTest.java

**Summary:**
The list of parameters displayed when calling the `--help` option should match the list described in [USAGE.md](https://github.com/MobilityData/gtfs-validator/blob/master/docs/USAGE.md).
Closes #1116 

fix: Update the "Help" menu with current command line parameters#1116

---

.github/workflows/acceptance_test.yml

Added missing commit from https://github.com/MobilityData/gtfs-validator/pull/1583

Repair acceptance test

---

docs/RELEASE.md

**Summary:**
This PR adds a step in the release documentation: updating the release number on https://gtfs.org/schedule/validate/
- ~~[ ] Linked all relevant issues~~

Docs: Add mention to update version number on gtfs.org

---

docs/BUILD.md

**Summary:**
Closes #1619 
Added a bit of documentation to refer to gtfs-validator-example.
For the reviewer please also take a look at https://github.com/MobilityData/gtfs-validator-example

feat: #1619 Added a bit of documentation to refer to gtfs-validator-example.

---

main/src/main/java/org/mobilitydata/gtfsvalidator/runner/ValidationRunner.java

**Summary:**
Closes #1647
When running the validator with multiple datasets (like in the web validator) we sometimes have errors in the results because the noticeContainer is shared between threads.

fix: Corrected a problem where code was not multithread safe

---

main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java

**Summary:**
Closes #1779 
Email with screenshot sent to reviewers due to data privacy.

fix: Count appears as 1 for block even when no blocks exist

---

main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFareLegRuleSchema.java

**Summary:**
Closes #1768 
- add rule priority to GtfsFareLegRuleSchema
- dataset and screenshot are not included here due to data privacy
- unknown_field not triggered in the report

feat: added new field for rule priority in GtfsFareLegRuleSchema

---

main/src/main/java/org/mobilitydata/gtfsvalidator/report/JsonReportSummary.java
main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java
main/src/test/java/org/mobilitydata/gtfsvalidator/report/model/JsonReportSummaryTest.java

**Summary:**
Closes #1849 
added feedServiceWindow to JSON report

feat: add feedServiceWindow to JSON report

---

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/BookingRulesEntityValidator.java

fix: keep the notice description as is

---

main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java

fix: filter out `Continuous Stops` from flex alert

---

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/DuplicateGeoJsonKeyNotice.java
main/src/main/java/org/mobilitydata/gtfsvalidator/table/GeoJsonFileLoader.java
main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsGeoJsonFeature.java
main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsGeoJsonFeaturesContainer.java
main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimesGeographyIdPresenceValidator.java
main/src/main/java/org/mobilitydata/gtfsvalidator/validator/UniqueGeographyIdValidator.java
main/src/test/java/org/mobilitydata/gtfsvalidator/table/GeoJsonFileLoaderTest.java
main/src/test/java/org/mobilitydata/gtfsvalidator/validator/NoticeFieldsTest.java
main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopTimeGeographyIdPresenceValidatorTest.java
main/src/test/java/org/mobilitydata/gtfsvalidator/validator/UniqueGeographyIdValidatorTest.java

**Summary:**
Added `duplicate_geography_id`, `duplicate_geo_json_key` and `forbidden_geography_id` notices.
[Test feed](https://github.com/user-attachments/files/18594039/tst.zip)

feat: `duplicate_geography_id`, `duplicate_geo_json_key` and `forbidden_geography_id` notices

---

core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsInput.java
core/src/main/java/org/mobilitydata/gtfsvalidator/notice/InvalidInputFilesInSubfolderNotice.java

**Summary:**
This PR updates the documentation for the invalid_input_files_in_subfolder notice to include common error scenarios and steps to resolve the error as requested [here](https://github.com/MobilityData/gtfs-validator/issues/1446#issuecomment-2654466156).
Closes #1446 

feat: update docs for invalid_input_files_in_subfolder
