README.md
**Summary:**
Allows you to easily see the latest build status of the master branch of the project (and others), and links to the CI results
When going to the README, I should be able to see a badge for the CI that shows current status and links to the CI results:
=> Add CI badge to the README

adapter/parser/src/test/java/org/mobilitydata/gtfsvalidator/parser/GtfsEntityParserTest.java, adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsSpecRepositoryTest.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ParseSingleRowForFileTest.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAllOptionalFilenameTest.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAllRequiredFilePresenceTest.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAllRowLengthForFileTest.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateHeadersForFileTest.java
**Summary:**
This PR makes the test classes more legible: we push the supporting code of test classes at the bottom of files. It allows to focus on the goal of the implemented tested without having to scroll through files to find said tests.
New "style"  (from file: ValidateAllRequiredFilePresenceTest.java) :
The behavior of the code does not change. Class constants and variables are still defined at the top of the files.
Linked issue: https://github.com/MobilityData/gtfs-validator/issues/56 
=> Fix #56 - Refactor test classes

application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java
**Summary:**
Currently the help text looks like:
> -z,--zip <arg>      if --url is used, where to place the downloaded
archive.Otherwise, relative path pointing to a valid
GTFS zipped archive on disk
There should be a space after the `.` and before `Otherwise`
After this change, a space is added:
> -z,--zip <arg>      if --url is used, where to place the downloaded
archive. Otherwise, relative path pointing to a valid
GTFS zipped archive on disk
=> Add space in help text

gradle/wrapper/gradle-wrapper.properties
**Summary:**
Enables the project to build on JDK 14
Previously (as discussed in #103), on JDK 14 building the project fails. This PR enables the project to build using JDK 14.
=> Fix #103 - Bump Gradle to 6.3

adapter/parser/src/main/java/org/mobilitydata/gtfsvalidator/parser/GtfsEntityParser.java, adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsSpecRepository.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/ParsedEntity.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/RawEntity.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAllRequiredFilePresence.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAllRowLengthForFile.java
**Summary:**
This change re-formats a few Javadocs so they compile using `./gradlew javadoc`. Fixes #106.
`./gradlew javadoc` now successfully completes:
=> Fix #106 - Fix javadocs so they compile

RELEASE.md, adapter/exporter/build.gradle, adapter/repository/in-memory-simple/build.gradle, application/cli-app/build.gradle
**Summary:**
~~*Work-in-progress - please do not merge*~~
This pull request adds the ability to do command-line releases using the [shadow Gradle plugin](https://github.com/johnrengelman/shadow).
Usage:
```
./gradlew shadowJar
```
...which will output a file to `\cli-app\build\libs` such as `gtfs-validator-v1.1.0-SNAPSHOT.jar`.
This file can then be run from the command-line with the normal Java conventions:
```
java -jar gtfs-validator-v1.1.0-SNAPSHOT.jar -u https://transitfeeds.com/p/mbta/64/latest/download -z input.zip -i input -o output
```
See the updated `RELEASE.md` file for more details.
TODO:
Closes #66, Closes #52
=> feat(Release): Enable command-line releases

application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java
**Summary:**
Prior to this patch, errors caught in the CLI `Main.main()` method were only partially output (see https://github.com/MobilityData/gtfs-validator/issues/112) - the type of the exception was missing.
For example, the output message looked like:
>[ERROR] 2020-04-15 17:06:38.743 [main] Main - An exception occurred: C:\git-projects\gtfs-validator\application\cli-app\build\libs\output\results.json
After this patch, the full error message is output:
>[ERROR] 2020-04-15 17:28:34.059 [main] Main - An exception occurred: java.nio.file.NoSuchFileException: C:\git-projects\gtfs-validator\output\results.json
The full caught exception type and message should be output to the command-line when running the validator.
=> chore: Improve CLI Main.main() error messages

usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/ExecParamRepository.java
**Summary:**
This PR fixes #117. We change the content of constant ZIP_KEY to be consistent with its use.
The validator now correctly handles the retrieval of values related to ZIP_KEY
=> Fix #117 - Change content of constant ZIP_KEY

config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java
**Summary:**
This PR fixes #124 by retrieving the gtfs specification ascii protobuf file content instead of passing the file name to the `InMemoryGtfsSpecRepo` constructor
=> Fix #124 - build InMemoryGtfsSpecRepo with resource content instead of name

domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/Agency.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/routes/Route.java, domain/src/test/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/AgencyTest.java, domain/src/test/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/RouteTest.java
**Summary:**
This PR removes the notice collection from the parametric constructor of gtfs entities builder. Therefore, the default parametric constructor will be used. 
Tests have been adapted to said change.
- [N/A] Include screenshot(s) showing how this pull request works and fixes the issue(s)
=> Implement #186 - Remove notice collection from gtfs entities builder parametric constructor

usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateRouteLongNameDoesNotContainOrEqualShortName.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateRouteLongNameDoesNotContainOrEqualShortNameTest.java
**Summary:**
This PR provides support to avoid throwing NPE with validating that field `route_short_name` is not contained in `route_long_name` or equal to that same field. 
To do so, we extend the filter to filter out route entities with null route_short_name. New test have been implemented, and existing tests have been adapted.
The rule is no longer executed on routes with null fields `route_short_name` or `route_long_name`, which prevents NPE to be thrown.
=> Fix #249 -- Prevent NPE when executing use case ValidateRouteLongNameDoesNotContainOrEqualShortName

domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/fareattributes/FareAttribute.java
**Summary:**
This PR provides support to avoid occasional NPE when executing use case `ProcessParsedFareAttribute`. 
This bug was caused by the type of variables used. In this case, `fare_attributes.transfer_duration` can be null.
To avoid this, reference type `Integer` should be used instead of primitive type `int` for argument of method `transferDuration`.
No NPE.
=> Fix #279 - Avoid occasional NPE when processing FareAttribute entitites.

adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryExecParamRepository.java, config/src/main/resources/default-execution-parameters.json, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/DownloadArchiveFromNetwork.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/LogExecutionInfo.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/UnzipInputArchive.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/ExecParamRepository.java
**Summary:**
This PR provides support to rework the nomenclature used for command line options.
- `zipinput` -> input
- class constant `ZIP_KEY` -> `INPUT_KEY` 
=> Implement #255 -- Rework  command line options nomenclature

adapter/parser/src/main/java/org/mobilitydata/gtfsvalidator/parser/JsonExecParamParser.java, adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryExecParamRepository.java, adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/InMemoryExecParamRepositoryTest.java, application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java, config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/PrintHelp.java
**Summary:**
This PR provides support to avoid the display of help text when not providing configuration file `execution-parameters.json`.
A new variable `executionParametersAsString` is defined. It is `null` when the file could not be find, or the `String `representation of the `.json` configuration file.
This variables is defined through a `try/catch`  block.
Additional logging information is provided regarding the absence/presence of said file.
When file `execution-parameter.json` is not provided 2 possible behavior are expected:
- command line options have been provided -> we use them as execution parameters
- command line options have not been provided -> default values for execution parameters should be used.
In both cases message `"Configuration file …
=> Fix #275 -- Handle absence of execution-parameters.json

RELEASE.md
**Summary:**
Following the merge of https://github.com/MobilityData/gtfs-validator/pull/253, we need to update the version name in the GitHub CI each release.
New release notes include instructions to bump CI version too.
=> Update release notes to include bumping CI version

RULES.md, adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporter.java, adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporter.java, adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporterTest.java, adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporterTest.java, adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepository.java, application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java, config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/NoticeExporter.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/ErrorNotice.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/CalendarEndDateBeforeStartDate.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/CalendarEndDateBeforeStartDateNotice.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateCalendarEndDateBeforeStartDate.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/GtfsDataRepository.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateCalendarEndDateBeforeStartDateNoticeTest.java
**Summary:**
~~*Please don't merge - work-in-progress*~~
This PR implements a new validation rule for https://github.com/MobilityData/gtfs-validator/issues/133 - checking if `calendar.txt` `end_date` is before `start_date`.
I'm following the documentation at https://github.com/MobilityData/gtfs-validator/pull/251.
Done (Steps 1-4):
TODO (Steps 5-8):
Closes #133
Execute a new rule for https://github.com/MobilityData/gtfs-validator/issues/133 checking if the calendar.txt record end date is before the start date.
**Other thoughts so far:** 
* Exporter test code, especially for protocol buffers, includes a lot of duplication
* In `ProtobufNoticeExporter`, maybe move inner class `ProtobufOutputStreamGenerator` to the top of the file so that new `export()` methods can …
=> Fix #251 - New rule - `calendar.txt` `end_date` is before `start_date`

.github/workflows/gradle.yml
**Summary:**
Change the CI configuration to run on pull requests coming from forks too
This should fix GitHub so it runs on pull requests from forks.
~~I'm opening this PR from a fork, but IIRC GitHub CI only runs using the config from the master branch. So we may need to merge this PR before we see any change.~~ **EDIT** Just kidding, it's working!
=> Fix #291 - Make GitHub CI run on fork pull requests

adapter/utils/src/main/java/org/mobilitydata/gtfsvalidator/timeutils/TimeConversionUtils.java, adapter/utils/src/test/java/org/mobilitydata/gtfsvalidator/timeutils/TimeConversionUtilsTest.java, application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java, config/build.gradle, config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ProcessParsedStopTime.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ProcessParsedStopTimeTest.java
**Summary:**
This PR provides support to execute use case `ProcessParsedStopTime`.
`GtfsDataRepository` should be filled with `StopTime` entities using time utility class. 
PR implements a singleton pattern for time utility class.
=> Implement #303 - Execute usecase ProcessParsedStopTime

.github/workflows/gradle.yml, RELEASE.md, build.gradle
**Summary:**
This PR adds artifact upload when running GitHub actions
- to retrieve test reports
- to deliver snapshot version
An artifact should be available on the job status page. Here for https://github.com/MobilityData/gtfs-validator/runs/916338961
=> Artifact upload. Test results

RULES.md, adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporter.java, adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporter.java, adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporterTest.java, adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporterTest.java, adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryRawFileRepository.java, config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/NoticeExporter.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/ErrorNotice.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/Notice.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/DuplicatedHeaderNotice.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateHeadersForFile.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/RawFileRepository.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateHeadersForFileTest.java
**Summary:**
close #129 
This PR adds a rule to check if a column is duplicated in an input file.
A `DuplicatedHeaderNotice` is built for each duplicate found, even for out of spec fields.
[MTBA_duplicated_agency_name.zip](https://github.com/MobilityData/gtfs-validator/files/4997168/MTBA_duplicated_agency_name.zip)
=> Implement Duplicate column (CSV rule)

RULES.md, adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporter.java, adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporter.java, adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporterTest.java, adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporterTest.java, application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java, config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/StopTimeArrivalTimeAfterDepartureTimeNotice.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/NoticeExporter.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/ErrorNotice.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/Notice.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/StopTimeArrivalTimeAfterDepartureTimeNotice.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateStopTimeDepartureTimeAfterArrivalTime.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateStopTimeDepartureTimeAfterArrivalTimeTest.java
**Summary:**
Implement validation use case for Departure Time after Arrival Time for a StopTime record (stop_times.txt)
Validates and adds a StopTimeArrivalTimeAfterDepartureTimeNotice if needed.
=> Implements #198 - Stop times Departure Time after Arrival Time verification

RULES.md, adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporter.java, adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporter.java, adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporterTest.java, adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporterTest.java, adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepository.java, application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java, config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/NoticeExporter.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/ErrorNotice.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/MissingTripEdgeStopTimeNotice.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateTripEdgeArrivalDepartureTime.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/GtfsDataRepository.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateTripEdgeArrivalDepartureTimeTest.java
**Summary:**
closes #205 
This PR contains the required changes to validate each trip first and last stop time in `stop_times.txt` define either or both fields `departure_time` or `arrival_time`
=> Implement start and end times verification for a trip

RULES.md, adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporter.java, adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporter.java, adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporterTest.java, adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporterTest.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/NoticeExporter.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/ErrorNotice.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/Notice.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/MissingCalendarAndCalendarDateFilesNotice.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAllRequiredFilePresence.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAllRequiredFilePresenceTest.java
**Summary:**
This PR provides support to verify that at least one of the two aforementioned files is present in the GTFS archive to validate.
An error notice should be generated when both files are missing.
=> Implement #341 -- Enforce presence of at least 1 out of 2 files `calendar.txt` and `calendar_dates.txt`

adapter/utils/src/main/java/org/mobilitydata/gtfsvalidator/timeutils/TimeUtilsImpl.java, adapter/utils/src/test/java/org/mobilitydata/gtfsvalidator/timeutils/TimeUtilsImplTest.java
**Summary:**
This PR provides support to solve to avoid wrong conversion of AM time
`timeUtils.convertIntegerToHMMSS(timeUtils.convertHHMMSSToIntFromNoonOfDayOfService("06:01:00"))`
returns `06:01:00` instead of `06:60:00`
=> Fix #347 - Time conversion of AM times 

RULES.md, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/routes/Route.java, domain/src/test/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/RouteTest.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateShortAndLongNameForRoutePresence.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateShortAndLongNameForRoutePresenceTest.java
**Summary:**
This PR provides support to prevent building `Route` entities with both `route_short_name` and `route_long_name` null or blank.
A notice should be generated at the building stage of such entities, and these should not be added to the gtfs data repository.
=> Implement #353 - Avoid building Route entities with both name fields blank/null

RULES.md, adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporter.java, adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporter.java, adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporterTest.java, adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporterTest.java, adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepository.java, application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java, config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/NoticeExporter.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/ErrorNotice.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/Notice.java, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/FeedInfoLangAgencyLangMismatchNotice.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAgencyLangAndFeedInfoFeedLangMatch.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateAgencyLangAndFeedInfoFeedLangMatchTest.java
**Summary:**
This PR provides support to check that `agency.agency_lang` and `feed_info.feed_lang` match.
=> Implement #131 - Check agency.agency_lang and feed_info.feed_lang match

.github/workflows/endtoend.yml, adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepository.java, application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java, config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/CreatePath.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ExportResultAsFile.java, usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/GenerateFilenameListToProcess.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ExportResultAsFileTest.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/GenerateFilenameListToProcessTest.java
closes #436 
**Summary:**
This PR aims at making end to end workflow executions persist our validation reports from each dataset tested.
It contains additional code to ensure the validation process attempts to read the data relevant to the report generation as early as possible in the process in the case it aborts
We should see the artifacts in the end to end GitHub Action workflow runs.
https://github.com/MobilityData/gtfs-validator/actions?query=workflow%3A%22End+to+end%22
=> Collect and persist validation reports artifacts

.circleci/config.yml, .github/workflows/test_pack_doc.yml, application/web-app/react-client/jest.config.js
closes #408 
**Summary:**
This PR provides support to build and collect js test coverage report using `jest`
Test coverage report should be built and the resultant artifact should be collected on GitHub and CircleCI
=> Implement #408 - Build and collect js test coverage reports

.github/workflows/docker.yml, .github/workflows/end_to_end.yml, adapter/repository/in-memory-simple/src/main/resources/gtfs_spec.asciipb, domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/fareattributes/FareAttribute.java
closes #400 
**Summary:**
This PR provides support to prevent the validator from generating a `MissingRequiredValueNotice` when `fare_attributes.transfer` is empty.
This PR:
- modifies `gtfs_spec.asciipb` to match the GTFS specification in the following ways:
-  [x] allow `fare_attributes.transfers` to be empty
No notice should be generated if `fare_attributes.transfers` is empty
=> Implement #400 - Allow `transfer` to be blank in fare_attributes

README.md
**Summary:**
This is a doc fix  (I believe?) to reference the correct step when forking and running validation on a new GTFS dataset on GitHub.
Following https://github.com/MobilityData/gtfs-validator#longer-version---step-by-step-through-github-web-ui-screenshots-coming-soon should reference the correct steps.
=> docs: Fix GitHub Actions section to reference the right step

usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ExportResultAsFile.java, usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ExportResultAsFileTest.java
closes #475 
**Summary:**
This PR provides support to include both `feed_info.feed_publisher_name` and `agency.agency_name` in the validation report name.
reports should be named as follows:
`agency.agency_name--feed_info.feed_publisher__timestamp.json`
sample usages:
`feed_info.feed_publisher_name__agency.agency_name + timestamp.json`
`agency.agency_name__timestamp.json`
`__timestamp.json`
=> Rework report name to include both feed_publisher_name and agency_name when available

core/build.gradle, main/build.gradle, processor/build.gradle
closes #509 
**Summary:**
This PR provides support to make gradle test task verbose
At execution, Gradle test task should display information regarding tests.
=> chore: Make gradle test task verbose

core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsFeedName.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/Notice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/type/GtfsColor.java, core/src/main/java/org/mobilitydata/gtfsvalidator/type/GtfsDate.java, core/src/main/java/org/mobilitydata/gtfsvalidator/type/GtfsTime.java
The contract for Object.hashCode states that if two objects are equal, then calling the hashCode() method on each of the two objects must produce the same result. Implementing equals() but not hashCode() causes broken behaviour when trying to store the object in a collection.
Affected classes:
* GtfsFeedName
* Notice
* GtfsColor
* GtfsDate
* GtfsTime
=> fix: Add hashCode() method to classes that implement equals()

main/src/main/java/org/mobilitydata/gtfsvalidator/notice/RouteBothShortAndLongNameMissingNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/RouteShortAndLongNameEqualNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/RouteShortNameTooLongNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/RouteNameValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/RouteNameValidatorTest.java
* RouteBothShortAndLongNameMissingNotice - Both short_name and long_name are missing for a route.
* RouteShortAndLongNameEqualNotice - Short and long name are equal for a route.
* RouteShortNameTooLongNotice - Short name of a route is too long (more than 6 characters).
=> feat: Validate long and short names for a single route

core/src/main/java/org/mobilitydata/gtfsvalidator/type/GtfsTime.java, main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFareAttributeSchema.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/Analyser.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/EnumGenerator.java
* Pattern is a deeply immutable type, so this field should be in UPPER_SNAKE_CASE (HHMMCC_PATTER).
* Methods and non-static variables should be named in lowerCamelCase.
* Using static imports for types is unnecessary
* Field name is CONSTANT_CASE, but field is not static and final
=> refactor: Fix style problems detected by Google linter

main/build.gradle
8 GiB is enough for validation of the largest feeds that contain 25 M stop times.
=> chore: Increase memory size up to 8 GiB

main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsStopTimeSchema.java
This PR provides support to specify field type for stop_times.trip_id as ID
=> fix: Specify field type for stop_times.trip_id as ID

.github/workflows/test_pack_doc.yml
**Summary:**
It's frustrating to sit around and wait for CI builds to finish when only documentation (markdown files) has changed.
This PR adds configuration to GitHub Actions to ignore any changes to documentation:
* If the change is to a .md file and it was started via a push or pull request, then don't run the GitHub Action CI build
* Release builds will still be executed even if the only changes are to .md files
=> ci: Don't run GitHub Action build on documentation changes

core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/CachedField.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/FieldCache.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/CsvFileTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/FieldCacheTest.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java, main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsStopTimeSchema.java, main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTranslationSchema.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/Analyser.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/EntityImplementationGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/FieldNameConverter.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/GtfsFieldDescriptor.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
There are many fields that repeat for multiple rows of a single table, e.g., stop_headsign for stop_times.txt or shape_id for shapes.txt. Caching of those values dramatically saves memory for large feeds, e.g., a feed with 25 M stop times requires 8 GiB without caching and 3 GiB with caching.
All tables are read in parallel, that's why we create a separate set of caches for each table. It is tempting to use the same cache for, e.g., trip_id in both trips.txt and stop_times.txt but that would require synchronization that slows down the reading.
The following fields are cached:
* annotated with @CachedField;
* types ID, date, time, color.
Primary keys are not cached since they are unique for each row.
=> feat: Cache certain field values to optimize memory usage

.github/workflows/end_to_end.yml
**Summary:**
This PR removes OV's dataset from the execution of the end-to-end workflow
No code change: workflow should not be executed on Netherlands dataset.
=> ci: remove OV's dataset from end to end workflow

.github/ISSUE_TEMPLATE/feature_request.md
**Summary:**
Currently `[REQUEST]` is prepended to all issue titles. It doesn't seem to serve any purpose so let's remove it.
When you open a feature request issue, `[REQUEST]` should no longer be autopopulated in the issue title.
=> docs: Remove "[REQUEST]" prefix from issue template

core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/FieldTypeEnum.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java, main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsAgencySchema.java, main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsStopSchema.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/AgencyConsistencyValidator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/Analyser.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/EntityImplementationGenerator.java
One should avoid using the date/time APIs in java.util.
This includes java.util.Date (and its subclass, java.sql.Timestamp),
java.util.Calendar, java.util.TimeZone, etc. They are bad APIs [1].
Even Oracle now acknowledges that these classes have "several
drawbacks" [2].
java.time is the best date/time library that Java offers. Compared to
JodaTime, it has better precision, better APIs, and is built directly
into the language.
[1] https://dzone.com/articles/game-over-jdks-date-and-time-c
[2] https://docs.oracle.com/javase/tutorial/datetime/iso/legacy.html
=> refactor: Migrate to java.time.ZoneId from java.util.TimeZone

core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsInput.java, core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsUnarchivedInput.java, core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsZipFileInput.java, core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsZipInMemoryInput.java, core/src/test/java/org/mobilitydata/gtfsvalidator/input/GtfsInputTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/input/GtfsUnarchivedInputTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/input/GtfsZipFileInputTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/input/GtfsZipInMemoryInputTest.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Arguments.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/CliParametersAnalyzer.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java, main/src/test/java/org/mobilitydata/gtfsvalidator/cli/CliParametersAnalyzerTest.java
java.nio.file.Path is a more flexible way to retrieve files and
directories.
ZIP file can be loaded to memory instead of being saved to a temporary
directory. This is useful when the ZIP is placed on a non-local file
system or has to be downloaded from the given URL.
=> feat: Use java.nio.file.Path and support loading of ZIP files to memory

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedLoader.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainerTest.java
Notice container is not thread-safe, otherwise it will slow down adding
new notices. Each thread now has its own instance of notice container.
When the thread ends, its container is added to the global one.
=> feat: Avoid race condition for notice containers

main/src/main/java/org/mobilitydata/gtfsvalidator/notice/OverlappingFrequencyNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFrequencySchema.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/OverlappingFrequencyValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/OverlappingFrequencyValidatorTest.java
closes #522
**Summary:**
This PR validates that trip frequencies do not overlap. 
Two entries X and Y in frequencies.txt are considered to directly overlap if X.start_time <= Y.start_time and Y.start_time < X.end_time.
=> feat: Validate that trip frequencies do not overlap

core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsFeedName.java, core/src/test/java/org/mobilitydata/gtfsvalidator/input/GtfsFeedNameTest.java
ISO 3166-1 Alpha 2 country code for the United Kingdom is "GB" but feed
names use "UK" instead.
=> feat: Support UK as a synonym for GB country code

core/src/test/java/org/mobilitydata/gtfsvalidator/input/GtfsInputTest.java
**Summary:**
Closes https://github.com/MobilityData/gtfs-validator/issues/584.
Delete file failures can happen due to local conditions like file locks and aren't related to validator performance, so this PR removes the assertions that check if the file has been successfully deleted.
=> fix: Don't fail test on failure to delete temp file

core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsUnarchivedInput.java
The returned stream encapsulates a DirectoryStream. If timely disposal
of file system resources is required, the try-with-resources construct
should be used to ensure that the stream's close method is invoked after
the stream operations are completed.
=> fix: Use try-with-resources for Files.list

main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTripSchema.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java
This will allow to quickly find all trips that belong to a given block.
This also fixes a bug in the code generator. There will be tests for the
processor in future but now the existing GTFS schema serves as the
integration test.
=> feat: Add indexing of trips on block_id

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java
This method is generated for single-entity file containers such as
GtfsFeedInfoTableContainer.
=> fix: Make the generated getSingleEntity() method public

core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/CsvFile.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableContainer.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/MatchingFeedAndAgencyLangValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/MatchingFeedAndAgencyLangValidatorTest.java
The previously used method isEmptyFile() tells if the whole text file is
empty. That crashed the Validator for a non-empty feed_info.txt file
that contains only the headers.
This commit adds documentation to isEmptyFile() and other methods in
GtfsTableContainer.
The unit test was changed to use the real TableContainer classes with
their real behaviour.
Closes https://github.com/MobilityData/gtfs-validator/issues/583
=> fix: Do not crash on 0 entities in feed_info.txt

core/build.gradle, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java, processor/build.gradle, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
FluentLogger is more flexible and professional than stdout and stderr.
Note that Main.java keeps printing to stdout because its information
should be visible to the user on screen.
=> chore: Use FluentLogger instead of stderr and stdout

core/src/main/java/org/mobilitydata/gtfsvalidator/util/ServicePeriod.java, core/src/test/java/org/mobilitydata/gtfsvalidator/util/ServicePeriodTest.java, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/BlockTripsWithOverlappingStopTimesNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/util/CalendarUtil.java, main/src/main/java/org/mobilitydata/gtfsvalidator/util/ServiceIdIntersectionCache.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/BlockTripsWithOverlappingStopTimesValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/util/CalendarUtilTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/util/ServiceIdIntersectionCacheTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/BlockTripsWithOverlappingStopTimesValidatorTest.java
closes #523, closes https://github.com/MobilityData/gtfs-validator/issues/362
This checks to see if any trips with the same block id have
overlapping stop times. Both trips have to be operating on the same
service day, as determined by comparing the service dates of the
trips.
=> feat: Add BlockTripsWithOverlappingStopTimesValidator

main/src/test/java/org/mobilitydata/gtfsvalidator/validator/BlockTripsWithOverlappingStopTimesValidatorTest.java
Test that BlockTripsWithOverlappingStopTimesValidator can handle trips
with 0 or 1 stop gracefully.
=> chore: Add a unit test for trips with 0 or 1 stop

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
Remove the temptation to inherit from automatically generated classes.
Generated children of GtfsEntity and their builders are already marked
as final.
This is a common pattern The AutoValue library also makes its generated
classes final.
=> fix: Make children of GtfsTableLoader and GtfsTableContainer final

main/src/main/java/org/mobilitydata/gtfsvalidator/notice/BlockTripsWithOverlappingStopTimesNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/LocationWithoutParentStationNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/PlatformWithoutParentStationNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/StationWithParentStationNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/WrongParentLocationTypeNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/BlockTripsWithOverlappingStopTimesValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/LocationTypeSingleEntityValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ParentLocationTypeValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/BlockTripsWithOverlappingStopTimesValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/LocationTypeSingleEntityValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/ParentLocationTypeValidatorTest.java
Additional context will help to generate clearer messages in
human-readable validation report.
Parameter order in the constructors was unified:
* csvRowNumber
* stopId
* stopName
* locationType
Affected notices:
* BlockTripsWithOverlappingStopTimesNotice
* LocationWithoutParentStationNotice
* PlatformWithoutParentStationNotice
* StationWithParentStationNotice
* WrongParentLocationTypeNotice
=> feat: Add more context to different notices

core/src/test/java/org/mobilitydata/gtfsvalidator/type/GtfsColorTest.java
closes #567 
**Summary:**
This PR provides additional unit tests for `GtfsColor` class
No code change, tests should pass.
=> test: unit test for GtfsColor

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/GtfsAnnotationProcessor.java
Google has use cases for that.
This restores https://github.com/MobilityData/gtfs-validator/commit/dcbe2f33371a319ed1d7e0df7565e769928ffa46
that was partially reverted in https://github.com/MobilityData/gtfs-validator/pull/604
=> fix: Support trivial enum that have a single value (#605)

main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsRouteSchema.java
closes #625 
**Summary:**
This PR provides support to require routes.route_type field
When creating a `GtfsRoute` entity, if `routes.route_type` is missing, a `MissingRequiredField` should be generated and added to the `noticeContainer`.
=> fix: update Route schema to require routes.route_type field

.github/workflows/formatting.yml, .github/workflows/test_pack_doc.yml
**Summary:**
Hopefully this should allow pushes of format commits on PRs from forks (to be tested after merge to master). See https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/.
Also move workflow to it's own file.
Hopefully closes https://github.com/MobilityData/gtfs-validator/issues/615.
=> ci: Change auto-formatter to pull_request_target

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/MatchingFeedAndAgencyLangValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/MatchingFeedAndAgencyLangValidatorTest.java
closes #594 
**Summary:**
This PR fixes an NPE thrown during langage verification
No NPE should be thrown when `agency.agency_lang` is not provided while executing `MatchingFeedAndAgencyLangValidator` use case
=> fix(NPE): check hasAgencyLang() before executing agencyLang() method

main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsStopTimeSchema.java, main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsStopTimeTimepointEnum.java
Old name: GtfsStopTimesTimepointEnum
New name: GtfsStopTimeTimepointEnum
By convention, all table names should be in singular in schema
definition.
=> fix: Change enum name to GtfsStopTimeTimepointEnum

core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/CsvFile.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableLoader.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/CsvFileTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/CsvRowTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/table/GtfsLevelTableLoaderTest.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
GTFS spec says:
Files should be encoded in UTF-8 to support all Unicode characters.
Files that include the Unicode byte-order mark (BOM) character are
acceptable. See http://unicode.org/faq/utf_bom.html#BOM for more
information on the BOM character and UTF-8.
The Unicode Standard permits the BOM in UTF-8, but does not require
or recommend its use. Byte order has no meaning in UTF-8, so its only
use in UTF-8 is to signal at the start that the text stream is
encoded in UTF-8, or that it was converted to UTF-8 from a stream that
contained an optional BOM.
=> feat: Support CSV files that start with UTF-8 BOM

RULES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/DuplicateRouteNameNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/DuplicateRouteNameValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/DuplicateRouteNameValidatorTest.java
closes #533
closes #534
**Summary:**
This PR provides code do implement the following validation rule:
- All routes should have different `routes.route_long_name`. If routes have the same `routes.route_long_name`, they must be different routes serving different areas; and must not be different trips of the same route or different directions of the same route.
Note that two routes can have the same `routes.route_long_name` if they do not belong to the same agency.
- All routes should have different `rouytes.route_short_name`. If routes have the same `routes.route_short_name`, they must be different routes serving different areas; and must not be different trips of the same route or different directions of the same route. 
Note that two routes can have the same `routes.route_short_name` if …
=> feat: verify unicity of routes.route_long_name and routes.route_short_name

RULES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/UnusedTripNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TripUsageValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TripUsageValidatorTest.java
closes #519
**Summary:**
This PR implements a new validation rule: all trips must be used in stop_times.txt
- trips that are not used in `stop_times.txt` should generate a notice
- trips that are used in `stop_times.txt` should not generate a notice
New notice: `UnusedTripNotice`
=> feat: check all trips are used in stop_times.txt

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/GtfsInputCreationError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/IOError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/URISyntaxError.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java
closes #548
Duplicated #602
**Summary:**
https://github.com/MobilityData/gtfs-validator/pull/596 introduced the concept of system errors. 
Those need to be added to the noticeContainer in the main method. 
This PR suggests code to proceed.
1. System errors should be added to the notice container
2. Reports should be generated and exported.
=> fix: add system errors to notice container

main/src/test/java/org/mobilitydata/gtfsvalidator/cli/CliParametersAnalyzerTest.java
**Summary:**
It currently randomly fails on CI. See https://github.com/MobilityData/gtfs-validator/issues/591.
Tests shouldn't randomly fail on CI
=> fix: Comment out flaky provideUrlAndInputCliParametersShouldReturnFalse()

RULES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/MissingTripEdgeNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/MissingTripEdgeValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/MissingTripEdgeValidatorTest.java
closes #516 
**Summary:**
This PR implements a new valdiation rule: "First and last stop of a trip must define both `arrival_time` and `departure_time` fields".
- a notice should be generated if a trip's first stop does not have value for `arrival_time` field
- a notice should be generated if a trip's first stop does not have value for `departure_time` field
- a notice should be generated if a trip's last stop does not have value for `arrival_time` field
- a notice should be generated if a trip's last stop does not have value for `departure_time` field
New notice: `MissingTripEdgeNotice`
=> feat: validate time fields for trips edges

RULES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/DuplicateRouteNameValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/DuplicateRouteNameValidatorTest.java
closes #535 
**Summary:**
This PR implements a new validation rule: no duplicate of combination of route names fields
- a notice should be generated if two GtfsRoute entities share the same values for fields `routes.route_short_name` and `routes.route_long_name`. 
=> feat: Duplicate combination of route names fields

RULES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/UnusableTripNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TripUsabilityValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TripUsabilityValidatorTest.java
closes #520 
**Summary:**
This PR implements a new validation rule: Trips must have more than one stop to be usable.
- a notice should be generated if a trip visits 0 or 1 stop only,
- no notice should be generated when a trip visitis at least 2 stops.
=> feat: Unusable trip

RULES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/MissingCalendarAndCalendarDateFilesNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/MissingCalendarAndCalendarDateValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/MissingCalendarAndCalendarDateValidatorTest.java
closes #525
**Summary:**
This PR implements a new validation rule: Missing both calendar_dates.txt and calendar.txt files
- a notice should be generated when both `calendar.txt` and `calendar_dates.txt` files are missing
-  no notice should be generated if at least one of said files is provided in the GTFS archive.
=> feat: Missing both calendar_dates.txt and calendar.txt files

RULES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/DecreasingStopTimeDistanceNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimeIncreasingDistanceValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopTimeIncreasingDistanceValidatorTest.java
closes #526
**Summary:**
This PR implement a new validation rule: Stop times in a trip should have increasing distance
When grouped by `stop_times.stop_sequence`, all stops of a given `stop_times.trip_id` should have increasing value for field `stop_times.shape_dist_traveled`, a notice should be generated and added to the `noticeContainer` if a stop times fails at this requirement.
New notice: `StopTimeIncreasingDistanceValidator`
=> feat: Stop times in a trip should have increasing distance

core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedContainer.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableContainer.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/BlockTripsWithOverlappingStopTimesValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/MatchingFeedAndAgencyLangValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/MissingCalendarAndCalendarDateValidatorTest.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
Results of file validations and cross-file validations require all feed
data to be parsed and loaded to memory. This is possible that some
required files are missing or some rows or headers failed to parse,
e.g., a required field is missing or a string cannot be parsed as integer.
This change is aborting validation process if some files failed to parse
to avoid misleading validation notices. The change also removes amount
of boilerplate regarding GTFS table status (empty file, missing file
etc.).
Example.
Consider we failed to parse a row trip.txt but there is another row
in stop_times.txt that references a trip. Then foreign key validator
may notify about a missing trip_id which would be very misleading for
the feed provider.
=> feat: Abort validation if some files failed to parse

core/build.gradle, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/RuntimeExceptionInLoaderError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidationContext.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/FeedExpirationDateValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/table/GtfsLevelTableLoaderTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/FeedExpirationDateValidatorTest.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
ValidationContext is a read-only object that describes the feed as
a whole and also some system properties relevant for validation.
Any validator may request to inject ValidationContext using the usual
@Inject annotation. We chose that instead of modifying the signature of
validate() method because most validators do not need this context and
we want to avoid a huge refactoring.
=> feat: Inject a context object to validators

RULES.md, main/build.gradle, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/StopTooFarFromTripShapeNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/util/GeospatialUtil.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTooFarFromTripShapeValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/util/GeospatialUtilTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopTooFarFromTripShapeValidatorTest.java
closes #521 
**Summary:**
> This PR implements the rule to check when a stop is too far from the trip shape.
> 
> [GTFS Best Practices](https://gtfs.org/best-practices/#shapestxt) say:
> 
> >Route alignments (in shapes.txt) should be within 100 meters of stop locations which a trip serves.
> 
> Data used in unit tests is available as GeoJSON on GitHub here (GitHub provides a toggle between text and map view):
> https://gist.github.com/barbeau/d9c0b90a26a3e2ba105cae5f0e8aec4a
> 
> ![image](https://user-images.githubusercontent.com/928045/90898729-f39c6780-e394-11ea-8e6e-407ce1d22caf.png)
> 
> If desired, you can visualize the buffer by exporting a JTS-version of the buffer in WKT format using code at https://gist.github.com/barbeau/d9c0b90a26a3e2ba105cae5f0e8aec4a#gistcomment-3425554 and …
=> feat:  Stop too far from trip shape

.github/workflows/test_pack_doc.yml
closes #720 
**Summary:**
This PR provides support to persist the cli app as an artifact in GitHub workflow
No code change. Application jar should be persisted after build.
✅ `.jar` is persisted after build
=> fix: to persist the cli app as an artifact in GitHub workflow

.github/workflows/test_pack_doc.yml, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/AgencyConsistencyValidatorTest.java
closes #722 
**Summary:**
This PR provides support to persist all tests reports as an artifact in GitHub workflow
No code change. Reports for failed tests should be persisted an an artefact in GitHub workflow.
✅ reports for failed are generated (https://github.com/MobilityData/gtfs-validator/pull/723/commits/91aa30bd17686c052ce3cc01f688b943d6762960)
✅ reports for failed test are persisted after running GitHub workflow
=> fix: paths to failed test reports

main/src/main/java/org/mobilitydata/gtfsvalidator/notice/FeedInfoLangAndAgencyLangMismatchNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/MatchingFeedAndAgencyLangValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/MatchingFeedAndAgencyLangValidatorTest.java
To tell the truth, agency_lang field is misleading and it would be great
to deprecate it in favour of feed_lang. That would be nice to encourage
using feed_lang and omitting agency_lang.
1. We add more context to the generated error. Now it is clear which
agency on which line is breaking the validation rule.
2. There are a lot of feeds that specify feed_lang and no agency_lang.
They are accepted after that change.
3. The existing http://gtfs.org/reference/static/#feed_infotxt does
not forbid having feed_lang="mul" and a single agency.
Consider a feed that covers Biel/Bienne, sets feed_lang=mul,
agency_lang='' and provides translations.txt for German and French.
=> feat: Accept the existing feeds in feed-and-agency-lang validator

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainerTest.java
Issue #549
Notices of different severities are grouped independently. This we make
sure that they the MAX_EXPORTS_PER_NOTICE_TYPE limit is applied to
errors and warnings independently.
We chose "severity" instead of "severityLevel" in the JSON format
because the former is shorter.
We also sort the exported notices alphabetically by code and severity.
This makes the report more readable (earlier we sorted them by hashes
that is stable but randomized).
=> feat: Export severity in JSON

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/EnumGenerator.java
This is a common Java recommendation that all generated classes should
have @Generated annotation.
=> feat: Put @Generated annotation on enums

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java
Some tables such as agency.txt and attributions.txt have optional
primary keys. When a key is set, it must be unique. At the same time,
several attributions are allowed to have no attribution_id.
Generated code for GtfsAttributionTableContainer.
```java
private void setupIndices(NoticeContainer noticeContainer) {
for (GtfsAttribution newEntity : entities) {
if (!newEntity.hasAttributionId()) {
continue;
}
GtfsAttribution oldEntity = byAttributionIdMap.getOrDefault(newEntity.attributionId(), null);
if (oldEntity != null) {
noticeContainer.addValidationNotice(new DuplicateKeyError(gtfsFilename(), newEntity.csvRowNumber(), oldEntity.csvRowNumber(), GtfsAttributionTableLoader.ATTRIBUTION_ID_FIELD_NAME, newEntity.attributionId()));
} else {
byAttributionIdMap.put(newEntity.attributionId(), …
```
=> feat: Support optional primary keys

RULES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/DuplicateFareRuleZoneIdFieldsNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/DuplicateFareRuleZoneIdFieldsValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/DuplicateFareRuleZoneIdFieldsValidatorTest.java
closes #356
**Summary:**
This PR implements a new validation rule: the combination of `fare_rules.origin_id`, `fare_rules.contains_id` and `fare_rules.destination_id` fields should be unique in GTFS file `fare_rules.txt`.
- a notice should be generated if two (or more rows) from GTFS files `fare_rules.txt` have duplicate value for the combination of  `fare_rules.origin_id`, `fare_rules.contains_id` and `fare_rules.destination_id` fields
=> feat: no duplicate for `fare_rules.txt` zone id fields

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NonAsciiOrNonPrintableCharNotice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java
Issue #549
An error in RowParser stops validation for the whole feed. However, if
ID has non-printable or non-ASCII characters, the feed may be still
successfully parsed and served to the end user.
We are lowering priority of NonAsciiOrNonPrintableCharNotice to WARNING
and modify RowParser so that it checks severity level of its notices.
We also simplify the code of asId function and reduce amount of calls to
row.asString from 3 to 1.
=> feat: Treat NonAsciiOrNonPrintableCharNotice as a warning instead of error

main/src/main/java/org/mobilitydata/gtfsvalidator/notice/InconsistentAgencyLangNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/InconsistentAgencyTimezoneNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/AgencyConsistencyValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/AgencyConsistencyValidatorTest.java
Some real-world feeds provide agency_lang only for some agencies and
omit it for the rest since this field is optional. Those feeds are
accepted at Google, that is why we relax the existing validation rule.
In general, agency_lang field should be discouraged and feed_lang should
be used instead.
=> feat: Allow agencies to omit agency_lang without errors

RULES.md, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/MissingFeedInfoDateNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/FeedServiceDateValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/FeedServiceDateValidatorTest.java
closes #733 
**Summary:**
This PR removes the requirements on feed_info.start_date and feed_info.end_date
No notice should be generated if  `feed_info.start_date` and `feed_info.end_date` is missing Also, both fields can be blank.
=> fix: remove requirement on feed_info.start_date and feed_info.end_date

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/LeadingOrTrailingWhitespacesNotice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/CsvFile.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java
feat: Strip leading and trailing whitespaces and emit a warning
GTFS reference says:
Remove any extra spaces between fields or field names. Many parsers
consider the spaces to be part of the value, which may cause errors.
GTFS Validator strips whitespaces from protected values. We do not
see any use case when such a whitespace may be needed. On the other
hand, some real-world feeds use trailing whitespaces for some values
and omit them for the others. This is causing the largest problem
when a primary key and a foreign key differ just by a whitespace:
it is clear that they are intended to be the same, that is why we
always strip whitespaces.
Note that this is a warning:
* not an error because the feed may be still parsed;
* not an info because leading and trailing whitespaces are …
=> feat: Strip leading and trailing whitespaces and emit an error

main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java
If the feed failed to parse, then most validators are not invoked
because when they operate on an incomplete feed, they may produce
misleading messages. That is why we need to show a big error box to
attract user's attention to that.
```
-----------------------------------------
|       !!!    PARSING FAILED    !!!      |
|   Most validators were never invoked.   |
|   Please see report.json for details.   |
-----------------------------------------
```
=> feat: Show a big error when parsing failed

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NewLineInValueNotice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java
GTFS reference requires that field values do not contain new lines or
carriage returns (\n or \r).
RFC4180 CSV allows to spread a value between multiple lines if it is
surrounded by double quotes. But on practice, the feeds that have
multiline values are actually omitting the closing quote. That makes
different parsers interpret the file in different ways, so we need to
detect such ambiguous data in the validator.
=> feat: Report errors for new lines and carriage returns in field values

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/EmptyRowNotice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/CsvRow.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
A CSV file may end with a row that contains only spaces and does not end
with a new line, so that row is actually empty. Univocity parser treats
that row as non-empty: it interprets it as a row with a single empty
column. It is unclear whether this is a bug or a feature.
RFC 4180 does not give a hint on how to treat such rows.
Here we handle such rows gracefully and show a warning since that CSV is
ambiguous.
=> feat: Handle final row that does not end with a newline

core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java
String.strip is available only from Java 11 while String.trim is more
portable.
The difference is tiny and we can neglect it in our context:
* trim() removes all characters that are less than or equal to 'U+0020'
(the space character)
* strip() uses Character.isWhitespace function, so it removes fewer
characters
=> fix: Use String.trim instead of String.strip

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ShapeIncreasingDistanceValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/ShapeIncreasingDistanceValidatorTest.java
closes #757 
**Summary:**
This PR provides support to fix #757
A `DecreasingShapeDistanceNotice` should be issued in the case described by the following table:
`shapes.txt` 
| `shape_id` 	| `shape_pt_lat` 	| `shape_pt_lon` 	| `shape_pt_sequence` 	| `shape_dist_traveled` 	|
|------------	|----------------	|----------------	|---------------------	|-----------------------	|
| s1         	| 0.0              	| 34.5              	| 2                   	| 45.0                  	|
| s1         	| 0.0              	| 56              	| 3                   	| 45.0                    	|
=> fix: equal distance generate notice

RULES.md, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/SeverityLevel.java
**Summary:**
Closes https://github.com/MobilityData/gtfs-validator/issues/762
Align SeverityLevel docs with RULES.md . Also fix a typo.
Definition of ERRORS, WARNINGS, and INFO in SeverityLevel Javadocs should match what we've implemented in code (see https://github.com/MobilityData/gtfs-validator/pull/726) and the documentation in RULES.md.
=> docs: Align SeverityLevel Javadocs with RULES.md

.github/workflows/end_to_end.yml, .github/workflows/end_to_end_100.yml, .github/workflows/end_to_end_big.yml, .github/workflows/test_pack_doc.yml, core/build.gradle, core/src/main/java/org/mobilitydata/gtfsvalidator/util/ServicePeriod.java, core/src/test/java/org/mobilitydata/gtfsvalidator/util/ServicePeriodTest.java, main/build.gradle, main/src/main/java/org/mobilitydata/gtfsvalidator/util/CalendarUtil.java, main/src/main/java/org/mobilitydata/gtfsvalidator/util/ServiceIdIntersectionCache.java, main/src/test/java/org/mobilitydata/gtfsvalidator/util/CalendarUtilTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/DuplicateRouteNameValidatorTest.java, processor/build.gradle
Google is still using the old Java.
The updated code was tested on OpenJDK 1.8.
=> chore: Downgrade to Java 8

main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopTooFarFromTripShapeValidatorTest.java
**Summary:**
The PRs for the switch to Java 8 (https://github.com/MobilityData/gtfs-validator/pull/759) and the changes to the rule for StopTooFarFromTripShape (https://github.com/MobilityData/gtfs-validator/pull/750) were open simultanouesly, so some Java 9 features snuck in as part of the changes to that rule.
Here's the build that failed on CI:
https://github.com/MobilityData/gtfs-validator/runs/1962540197
This PR removes the Java 9 feature (`Set.of()`) that caused the failure.
Only Java 8 compatible language features should be used.
=> fix: Remove Set.of()

core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java
**Summary:**
These are based on real-world values seen in the OpenOV Netherlands feed, as well as questions OpenOV asked about whether certain values would validate. OpenOV confirmed the correct behavior and will update their feed.
Additional unit tests are included that verify behavior on specific phone numbers with the "nl" region.
=> chore: Add additional unit tests for phone number

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/EmptyColumnNameNotice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/TableHeaderValidator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/TableHeaderValidatorTest.java
Consider a header row:
stop_id,stop_name,
Its third column does not have a name. We ignore it in the same way as
we ignore unknown columns but we need to emit a clear warning for that.
=> feat: Emit a warning for empty column name

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/DuplicateRouteNameValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/DuplicateRouteNameValidatorTest.java
closes #754 
**Summary:**
This PR provides changes to rework rue implemented in `DuplicateRouteNameValidator`.
- `route.route_type` should be taken into consideration when checking for duplicate route names
- the validator is case sensitive when it comes to check different agency IDs. `agenCY id` and `AgencY id` are different following https://github.com/MobilityData/gtfs-validator/pull/689#discussion_r577701672
=> fix: route name validator

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java
**Summary:**
Closes https://github.com/MobilityData/gtfs-validator/issues/508
The goal of this PR is to make the sorting of GTFS entities that have been annotated with `@SequenceKey` more transparent in List data structures. Currently for a developer writing a new rule it's not clear whether they are responsible for sorting entities like GtfsShape by shapePtSequence in the rule implementation or if those entities have already be sorted in preprocessing.
This PR adds code to auto-generate Javadocs for methods in auto-generated container classes that return Lists of GTFS entities to make it clear which have been sorted, and by what field. This should hopefully result in less uncertainty for developers implementing new rules and should avoid potential performance pitfalls of sorting being …
=> docs: Add auto-gen Javadocs for Lists of @SequenceKey fields

RULES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/notice/AttributionWithoutRoleNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/AttributionWithoutRoleValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/AttributionWithoutRoleValidatorTest.java
closes #785 
**Summary:**
This PR implements the rule from `v1.4.0`which checked that all rows from GTFS file `attributions.txt` set a value to 1 to at least one of the following fields: 
- is_producer
- is_authority
- is_operator
- Attributions with no role defined should generate a notice
- Attributions with all roles set to 0 should generate a notice
- Attribution with a role (at least one of the aforementioned fields is set to 1) should not generate a notice
New notice: `AttributionWithoutRoleNotice`(with SeverityLevel set to `WARNING`)
=> feat: check all attributions have a role

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/EntityImplementationGenerator.java
Most of fields in entity classes never have null values: they are
initialized to "", 0 etc. This is made to avoid NullPointerException.
Users should call hasFIELD() method to check if a field is assigned.
Sample of generated code:
```
@Override
@Nonnull
public ZoneId agencyTimezone() {
return agencyTimezone;
}
public boolean hasAgencyTimezone() {
return (bitField0_ & 0x8) != 0;
}
@Override
@Nullable
public Locale agencyLang() {
return agencyLang;
}
public boolean hasAgencyLang() {
return (bitField0_ & 0x10) != 0;
}
```
=> feat: Add Nullable or Nonnull annotation to entity classes

main/src/main/java/org/mobilitydata/gtfsvalidator/notice/AttributionWithoutRoleNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/AttributionWithoutRoleValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/AttributionWithoutRoleValidatorTest.java
AttributionWithoutRoleValidator validates a single attribution. It does
not need the whole file to be scanned.
* SingleEntityValidators are invoked just after a row is parsed.
* FileValidators need the whole file to be scanned. They are skipped if
any row failed to parse or primary keys are non-unique.
=> fix: Inherit AttributionWithoutRoleValidator from SingleEntityValidator

core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/ForeignKeyValidatorGenerator.java
Because Java has specific, well-defined semantics for constructors
and how they relate to instance creation, constructor injection is
the simplest and most predictable form of dependency injection:
* Only one injectable constructor can exist per class
* Constructor injection must happen exactly once per instance
* Constructor injection can set final fields, which guarantees
that a dependency has been injected. In real-world software,
this is decidedly to your advantage.
The existing validator classes will be updated in a separate commit.
Support for injectable fields will be eventually removed.
=> feat: Support injectable constructors

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/DuplicateRouteNameValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/DuplicateRouteNameValidatorTest.java
closes #805 
**Summary:**
This PR provides changes to improve `DuplicateRouteNameValidator`
Routes are stored by the hashcode associated to:
- route_short_name, route_type instead of the concatenation of both fields
- route_long_name, route_type instead of the concatenation of both fields
- route_long_name, route_short_name, route_type instead of the concatenation of these 3 fields
Same tests should pass as there is no other logic change. 
=> chore: improve efficiency of DuplicateRouteNameValidator

main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsStopSchema.java, main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsStopTimeSchema.java
That will allow us to find all child stops of a station and all stop
times that belong to the same stop.
```
stopTable.byParentStation("station1")
stopTimeTable.byStopId("stop1")
```
Also reorder some annotations. We would like to have the following
common order:
* FieldType
* PrimaryKey, FirstKey or SequenceKey
* Index
* Required or ConditionallyRequired
* ForeignKey
=> feat: Add indices on stop.parent_station and stop_times.stop_id

.github/ISSUE_TEMPLATE/new-validation-rule.md
Adds a new issue template option to the "New issue" workflow.  The options after this is merged are:
1. Bug report
2. Feature request
3. New validation rule
Closes https://github.com/MobilityData/gtfs-validator/issues/816
=> docs: Add issue template for new validation rules

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TripUsageValidator.java
**Summary:**
This PR removes an import statement that does not belong to `TripUsageValidator` class.
Not code change.
=> chore: remove not used import statement

.github/workflows/end_to_end_100.yml
Relates to #835 
**Summary:**
This PR changes the URL used to validate PTV's dataset (Melbourne) as a temporary bug fix.
No OOM error. 
=> ci: change url for PTV dataset in end_to_end 100

README.md
**Summary:**
Previously we didn't have the v2 JAR for people to use, so we had IntelliJ instructions for setting up a Run configuration, etc.
This PR replaces the IntelliJ instructions with steps people can take to install Java and run the v2 release JAR.
It also adds a Rules section to the README, as this is what most users will be interested in (after running the validator).
I also moved "Build the code" towards the bottom near "Architecture", as fewer people are probably interested in that.
Users should be able to download and execute the v2 JAR using instructions on the README.
=> docs: Update README for executing v2 JAR

main/src/test/java/org/mobilitydata/gtfsvalidator/util/CalendarUtilTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/AttributionWithoutRoleValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/DuplicateRouteNameValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/LocationTypeSingleEntityValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/ParentLocationTypeValidatorTest.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/EntityImplementationGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/FieldNameConverter.java
Entity Builder classes are used in two contexts:
* in autogenerated Loader classes;
* in unit tests.
Loader classes call setFieldName() methods that accept Integer. But for unit tests, it is more convenient to pass the enum.
```
@Nonnull
public GtfsPathway.Builder setPathwayMode(@Nullable Integer value) {
if (value == null) {
return clearPathwayMode();
}
pathwayMode = value;
bitField0_ |= 0x8;
return this;
}
@Nonnull
public GtfsPathway.Builder setPathwayMode(@Nullable GtfsPathwayMode value) {
return value == null ? clearPathwayMode() : setPathwayMode(value.getNumber());
}
@Nonnull
public GtfsPathway.Builder clearPathwayMode() {
pathwayMode = DEFAULT_PATHWAY_MODE;
bitField0_ &= ~0x8;
return this;
}
```
=> feat: Provide enum setters and clearFIELD methods

docs/USAGE.md, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Arguments.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java, main/src/test/java/org/mobilitydata/gtfsvalidator/cli/ArgumentsTest.java
**Summary:**
This PR provides support to override naming of report outputs.
Additional CLI args : 
* `-v` or `--validation_report_name` - the value given to this CLI args should include `.json` extension;
* `-e` or `system_errors_report_name` - the value given to this CLI args should include `.json` extension.
If provided: the reports will be named as defined by the user, else a default value are used: 
* `report.json` for the validation report
* `system_errors.json` for the error report
=> feat: make report names user configurable via CLI args

core/build.gradle, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/CsvFile.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/CsvHeader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/CsvRow.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableContainer.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/TableHeaderValidator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/CsvFileTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/CsvHeaderTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/CsvRowTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/TableHeaderValidatorTest.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
Some validation rules may need to check whether a certain column is
present. E.g., this can allow them to skip further validation.
Unit tests are simplified and mocks are removed.
=> feat: Make file headers available in CSV table containers

.github/workflows/end_to_end.yml, .github/workflows/end_to_end_100.yml, .github/workflows/end_to_end_big.yml
closes https://github.com/MobilityData/gtfs-validator/issues/860
**Summary:**
This PR provides support to fix failing end-to-end workflows due to the latest deprecation of `--feed_name` CLI parameter in #852.
end-to-end workflows should be successfully executed.
=> fix: end to end workflows

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/InvalidEmailNotice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/InvalidPhoneNumberNotice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/InvalidUrlNotice.java
Pass severityLevel to constructor of notices for invalid email, phone and URL.
Some clients (e.g, Google) may want to reduce severity to WARNING.
=> feat: Pass severityLevel to constructor of some notices

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/Notice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultFieldValidator.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultTableHeaderValidator.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultValidatorProvider.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/GtfsCellContext.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/GtfsFieldValidator.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorProvider.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorUtil.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/DefaultFieldValidatorTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/TableHeaderValidatorTest.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java, main/src/test/java/org/mobilitydata/gtfsvalidator/table/GtfsLevelTableLoaderTest.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
We pass a single ValidatorProvider object instead of ValidatorContext
and ValidatorLoader. This allows us to achieve a list of goals.
1. Better modularity and testability. It is possible to inject a custom
ValidatorProvider in the tests.
2. Clients may provide their own validation for phones, emails etc.
3. We open a way to define custom table header validators.
4. We will introduce a concept of critical validators (e.g., foreign key
integrity) that will run before all other validators.
5. ValidationContext is now used in a small amount of files, so it will
be easier to split it into smaller classes.
=> feat: Dependency injection with ValidatorProvider

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/LeadingOrTrailingWhitespacesNotice.java
Some users (e.g., Google) may want to reduce severity to WARNING.
=> feat: Pass severity to constructor of LeadingOrTrailingWhitespacesNotice

core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidationContext.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoaderException.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/FeedExpirationDateValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/table/GtfsLevelTableLoaderTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/FeedExpirationDateValidatorTest.java
1. Inject individual objects like CurrentDateTime instead
of the whole ValidationContext. This makes dependencies
more explicit since a validator requires just a
certain part of the potentially large ValidationContext.
2. Validate that all validator constructors accept parameters
of supported types and throw an exception for any invalid
validator. This prevents hidden bugs when a validator cannot
be instantiated but nobody notices that because a file for
the corresponding validator is not present.
=> feat: Inject individual objects and validate the constructors

core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedLoader.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java
InterruptedException is a sign to immediately stop validation. We may not just add a notice and keep on validating.
IBM wrote an article on the subject:
http://web.archive.org/web/20210201071452/https://www.ibm.com/developerworks/java/library/j-jtp05236/index.html
If throwing InterruptedException means that a method is a blocking method, then calling a blocking method means that your method is a blocking method too, and you should have a strategy for dealing with InterruptedException. Often the easiest strategy is to throw InterruptedException yourself, as shown in the putTask() and getTask() methods in Listing 1. Doing so makes your method responsive to interruption as well and often requires nothing more than adding InterruptedException to your throws clause.
=> feat: Propagate InterruptedException during feed loading

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/IOError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/RuntimeExceptionInLoaderError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/RuntimeExceptionInValidatorError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/ThreadExecutionError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/ThreadInterruptedError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/URISyntaxError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorUtil.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainerTest.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java
Throwable.getMessage() can return null but ImmutableMap may not keep
nulls, so we store "" instead.
We pass an exception instance to the constructors for convenience.
Note that ThreadInterruptedError was not updated since we plan to remove
it.
=> fix: Prevent NullPointerException when Throwable.getMessage returns null

core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultFieldValidator.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/GtfsFieldValidator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/DefaultFieldValidatorTest.java
If an error is stored to the NoticeContainer, then it is already clear
that the field is invalid. Returning an additional boolean is redundant
and may lead to bugs when the function returns false but no error
notices are emitted.
=> feat: Simplify validator functions

core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java
There are no unchecked type conversions in the annotated functions.
=> fix: Remove redundant SuppressWarnings

core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidationContext.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/ValidationContextTest.java
Consider we want to inject a ChildCurrentDateTime class. This assignment
is invalid:
ChildCurrentDateTime param = new CurrentDateTime();
It may be only the other way:
CurrentDateTime param = new ChildCurrentDateTime();
See also the valid implementation:
```
private static boolean isInjectableFromContext(Class<?> parameterType) {
return parameterType.isAssignableFrom(CurrentDateTime.class)
|| parameterType.isAssignableFrom(CountryCode.class);
}
```
=> fix: Swap arguments of isAssignableFrom

RULES.md, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/CsvParsingFailedNotice.java, main/build.gradle, processor/build.gradle, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
If a CSV file failed to parse, there will be a clear user-visible
notice, e.g.:
```
{
"code": "csv_parsing_failed",
"severity": "ERROR",
"totalNotices": 1,
"notices": [
{
"filename": "stops.txt",
"charIndex": 278201,
"columnIndex": 2,
"lineIndex": 2148,
"message": "Length of parsed input (4097) exceeds the maximum number of characters defined in your parser settings (4096).",
"content": "..."
}
]
}
```
=> feat: Catch CSV parse errors and add validation notices

.github/workflows/docker.yml, Dockerfile
closes #844 
**Summary:**
This PR provides support to bump debian version used in docker image.
Pull the image generated for this bug fix:
1. `docker pull ghcr.io/mobilitydata/gtfs-validator:fix-debian-version-used-in-docker-image
`
2. Run `cat /etc/issue` to see Debian version.
Debian version is 10 🎉
=> fix: bump debian version used in docker image

docs/USAGE.md, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Arguments.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java
closes #857 
**Summary:**
This PR provides support to print help menu 
Print help if `-h` is provided as a CLI parameter. Such help should describe the usage of each CLI parameter. When provided, presence of required parameters should not be checked.
Running the validator with the following CLI parameters:
* `-h`;
* `--help`;
* `-u http://webapps.thebus.org/transitdata/Production/google_transit.zip -o output -t 4 -h`;
*  or `-u http://webapps.thebus.org/transitdata/Production/google_transit.zip -o output -t 4 --help` produce the following output:
=> feat: print help menu

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainerTest.java
Some notices may have special double values (NaN, Infinity, -Infinity)
in the context. If we do not allow their serialization, then an attempt
to store validation results ends up with a runtime exception.
Documentation for GSON library says the following.
Section 2.4 of <a href="http://www.ietf.org/rfc/rfc4627.txt">JSON specification</a> disallows
special double values (NaN, Infinity, -Infinity). However,
<a href="http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf">Javascript
specification</a> (see section 4.3.20, 4.3.22, 4.3.23) allows these values as valid Javascript
values. Moreover, most JavaScript engines will accept these special values in JSON without
problem. So, at a practical level, it makes sense to accept these values as valid JSON even
though JSON …
=> feat: Export infinity and NaN values in JSON

core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java
This is a performance improvement: this way we do not create a
temporary NoticeContainer object for each string value.
This affects the following functions:
* asLatitude
* asLongitude
* asUrl
* asEmail
* asPhoneNumber
These functions were returning null for invalid values just for
consistency with such functions as asLanguageCode or asTimezone that
are not able to return a valid Locale or ZoneId object for invalid field
values.
There is no practical need to return null for invalid values. A
TableLoader creates a separate NoticeContainer instance per each row and
if there are any errors for any cell, the whole row is considered
invalid.
=> feat: Return non-null for invalid strings and doubles

main/src/main/java/org/mobilitydata/gtfsvalidator/util/CalendarUtil.java, main/src/test/java/org/mobilitydata/gtfsvalidator/util/CalendarUtilTest.java
ServicePeriod constructor throws an exception for start and end date in
wrong order. There is a dedicated GtfsCalendarEndRangeValidator, so an
error is reported to the end user. This change avoids throwing an
exception in other validators that rely on CalendarUtil.
=> fix: Protect against start_date and end_date in wrong order

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java
Store up to 10 M validation notices. This is a measure to prevent OOM
in the rare case when each row in a large file (such as stop_times.txt
or shapes.txt) produces a notice. Since this case is rare, we just
introduce a total limit on the amount of notices instead of counting
amount of notices of each type.
Note that system errors are not limited since we don't expect to have
a lot of them.
Now we have a boolean field to flag if there are validation errors. This
way hasValidationErrors() now takes O(1) instead of O(n).
We also documented the methods and return unmodifiableList from getters.
We cannot use ImmutableList since the notice lists are always growing.
=> feat: Prevent OOM in NoticeContainer and speed up hasValidationErrors

core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultTableHeaderValidator.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/TableHeaderValidator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/TableHeaderValidatorTest.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
This simplifies the implementation logic and prevents potential bugs
when the function returns true ("valid") but adds some errors to the
container or vice versa.
Note that GtfsFieldValidator follows the same pattern: its validation
methods return void and the caller must use
NoticeContainer.hasValidationErrors.
Sample generated code.
```
NoticeContainer headerNotices = new NoticeContainer();
validatorProvider
.getTableHeaderValidator()
.validate(FILENAME, header, getColumnNames(), getRequiredColumnNames(), headerNotices);
noticeContainer.addAll(headerNotices);
if (headerNotices.hasValidationErrors()) {
return new GtfsCalendarTableContainer(GtfsTableContainer.TableStatus.INVALID_HEADERS);
}
```
=> feat: Return void from TableHeaderValidator.validate

core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableContainer.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
EmptyFileNotice is already an ERROR.
We have verified on 3K feeds at Google that none provides empty CSV file
(i.e. a file that contains no rows and no headers). We do not see a use
case for empty files in GTFS.
Since an empty file is an error, we do not invoke single-file validators
for it. Cross-file validations will not be invoked if any file is
completely empty.
In future we may merge EMPTY_FILE, INVALID_HEADERS and UNPARSABLE_ROWS
into a single constant.
=> feat: Treat empty files as parsed unsuccessfully

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainerTest.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Arguments.java, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java, main/src/test/java/org/mobilitydata/gtfsvalidator/cli/ArgumentsTest.java
closes #838 
**Summary:**
This PR provides support for an additional CLI parameter : `-p`/ `--pretty` which takes no value. This is used to bautfy the generated reports.
Sample usage 
```
-u http://webapps.thebus.org/transitdata/Production/google_transit.zip -t 4 -p -o output
```
=> feat: introduce -p CLI parameter to output beautified reports

RULES.md, docs/NEW_RULES.md, docs/NOTICES.md
closes #849 
**Summary:**
This PR provides additional documentation for notices.
**TODOs**
=> docs: document ERROR notices

.github/workflows/docker.yml
Relates to https://github.com/MobilityData/gtfs-validator/pull/905
**Summary:**
At present, a new Docker image is only published at release. Said docker image should be published on every commit on the `master` branch. 
A new Docker image should be published each time a branch is merged to `master`. 
- Running `docker pull ghcr.io/mobilitydata/gtfs-validator` should automatically point to the latest version of the docker image. 
- The `latest` version should be available on [this page](https://github.com/MobilityData/gtfs-validator/pkgs/container/gtfs-validator)
- ~[] Linked all relevant issues~
- ~[ ] Include screenshot(s) showing how this pull request works and fixes the …
=> ci: publish a new docker image on every push on master

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/CsvParsingFailedNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/BlockTripsWithOverlappingStopTimesValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/DuplicateRouteNameValidator.java
This relates to #899 
**Summary:**
This PR provides additional constructors to notices such as:
-  `CsvParsingFailedNotice`
- `DuplicateRouteNameNotice`
- `BlockTripsWithOverlappingStopTimesNotice` 
This change is the following: in the process to extract metadata from the `ValidationNotice` subclasses, we intend to leverage the constructor's parameters. However, the aforementioned notices use take exceptions or GtfsRoute as parameters (from which information is extracted in the call to `super`). Having this additional constructor allows to directly extract information about the parameters for said notices from their constructor.
No changed behavior.
- ~[ ] Include screenshot(s) …
=> refactor: add standardized constructor to notices

RULES.md, docs/NOTICES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopNameValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopNameValidatorTest.java
closes #910 
**Summary:**
This PR provides support to implement a new rule described in #910 
New `ValidationNotice`: `SameNameAndDescriptionForStopNotice` (severity level: `WARNING` - to be upgraded to `ERROR` in the future. 
A notice should be generated for each record from `stops.txt` where `stops.stop_des == stops.stop_name`.
=> chore: check stop name and desc

RULES.md, docs/NOTICES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidatorTest.java
closes #237 
**Summary:**
This PR provides support to implement https://github.com/MobilityData/gtfs-validator/issues/237
New notice: 
- `StopWithoutZoneIdNotice` (severity level = `WARNING` - to be upgraded to `ERROR` in the future).
Per GTFS specification, `stops.zone_id` should be provided if fare information is provided using `fare_rules.txt` - if this requirement is not met, a notice should be emitted. 
Note that this rule does not apply to records from `stops.txt` that represent a stop or en entrance (i.e. `stops.location_type = 1 or 2`) - in this case, no notice should be emitted.
Gtfs specification reference:
> |  `zone_id` | ID | **Conditionally Required** | Identifies the fare zone for a stop. If this record represents a station or station entrance, the …
=> chore: check stops.zone_id presence

RULES.md, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/LeadingOrTrailingWhitespacesNotice.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java, docs/NOTICES.md
closes #920 
**Summary:**
This PR downgrades `LeadingOrTrailingWhitespacesNotice` to WARNING.
=> chore: downgrade LeadingOrTrailingWhitespacesNotice to WARNING

main/build.gradle, processor/build.gradle
The previously used dependency at io.sgr was not owned nor maintained by
Google.
The Google-owned library now lives at
com.google.geometry:s2-geometry:2.0.0.
=> chore: Use the latest version of s2-geometry library from Google-owned location

main/build.gradle
=> fix: add compileJava option to main/build.gradle

RULES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimeTravelSpeedValidator.java
* Raise speed threshold for unknown vehicle type to 200 km/h
* Set aerial lift and funicular threshold to 50 km/h
* Lower cable tram threshold to 30 km/h
GTFS Validator emits warnings for unknown vehicle types. Numerous
providers use extended route types [1]. This change effectively disables
speed checks for them by setting a high threshold. We can revisit this
later and add support for extended route types, as in Google adoption of
the open-source validator.
[1] https://developers.google.com/transit/gtfs/reference/extended-route-types
=> feat: Split the default 50 km/h threshold

core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/NoticeExport.java
It was replaced by SchemaExport that was removed.
=> fix: Remove unused annotation NoticeExport

.github/workflows/end_to_end_100.yml
**Summary:**
This PR adds memory while running the validator on ci. 
No OOM when executing the validator on Flanders' gtfs dataset (https://openmobilitydata.org/p/vlaamse-vervoersmaatschappij-de-lijn/530) 
=> ci: add 6GiB for ci runs

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainerTest.java, main/build.gradle, main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java
The caller can decide how to format JSON string:
* pretty printing
* HTML safe (escape <>&=)
* lenient
* etc.
=> feat: Return JsonObject from NoticeContainer methods

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/Notice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeSchemaGenerator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainerTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeSchemaGeneratorTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/testnotices/DoubleFieldNotice.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/testnotices/GtfsTypesValidationNotice.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/testnotices/StringFieldNotice.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/testnotices/TestValidator.java
It is currently not plugged into cli/Main.java.
The schema generator uses Java reflection to find all notice 
classes and describe their fields.
The schema generator currently exports JSON schema for the notices. It
may also export other schema formats in future (e.g., SQL-friendly
schema).
Sample output.
```
{
"attribution_without_role": {
"type": "object",
"properties": {
"attributionId": {
"type": "string"
},
"csvRowNumber": {
"type": "integer"
}
}
},
"block_trips_with_overlapping_stop_times": {
"type": "object",
"properties": {
"blockId": {
"type": "string"
},
"csvRowNumberA": {
"type": "integer"
},
"csvRowNumberB": {
"type": "integer"
},
"intersection": {
"type": "string"
},
"serviceIdA": {
"type": "string"
},
"serviceIdB": {
"type": "string"
},
"tripIdA": {
"type": "string"
}, …
```
=> feat: Add NoticeSchemaGenerator

main/build.gradle
Gson is used instead of Jackson.
Jackson2 has a terrible security record, with new remote code execution
vulnerabilities being published once every other month:
https://medium.com/@cowtowncoder/on-jackson-cves-dont-panic-here-is-what-you-need-to-know-54cd0d6e8062
=> fix: Remove unused dependency on jackson-databind

main/src/main/java/org/mobilitydata/gtfsvalidator/util/StopUtil.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimeTravelSpeedValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/util/StopUtilTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopTimeTravelSpeedValidatorTest.java
Also move getStopOrParentLatLng to a separate class to make it reusable.
=> chore: Protect against infinite loop in getStopOrParentLatLng

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/Notice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeSchemaGenerator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeSchemaGeneratorTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/testnotices/S2LatLngNotice.java
We will add notices with S2LatLng fields and we need to serialize them
to JSON. An S2LatLng will be serialized as array of two numbers:
latitude and longitude, in degrees:
```
"montreal": [45.505331312, -73.55249779]
```
This is similar to GeoJSON format for points:
```
"geometry": {
"type": "Point",
"coordinates": [102.0, 0.5]
}
```
=> feat: Serialize S2LatLng fields in Notice subclasses

.github/workflows/docker.yml, .github/workflows/end_to_end.yml, .github/workflows/end_to_end_100.yml, .github/workflows/end_to_end_big.yml, .github/workflows/test_pack_doc.yml
relates to #734 
**Summary:**
This PR provides support to verify the gradle wrapper by adding a job to the `test_pack_doc`workflow.
> This adds additional security/integrity to ensure that any changes to the wrapper match an official Gradle release.
(from https://github.com/MobilityData/gtfs-validator/pull/963#pullrequestreview-731891885)
Said job is required to execute test, packaging and documentation jobs. 
Workflows fail if the SHA-256 checksum does not match an official release from Gradle. 
=> ci: verify gradle wrapper 

RULES.md, docs/NOTICES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/LevelPresenceValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/LevelPresenceValidatorTest.java
**Summary:**
This PR provides support to verify conditionnal requirements on `levels.txt`. 
- `levels.txt` must be provided and non-empty if a row from `pathways.txt` has `pathways.pathway_mode=5`.
=> feat: verify conditional requirement of levels.txt presence

RULES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayEndpointTypeValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/PathwayEndpointTypeValidatorTest.java
* a pathway may not lead to a station (location_type=1);
* if a platform has boarding areas, the pathway must be connected to
its boarding areas instead of the platform itself.
=> feat: Validate that pathway endpoints have correct types

core/src/main/java/org/mobilitydata/gtfsvalidator/type/GtfsDate.java, core/src/test/java/org/mobilitydata/gtfsvalidator/type/GtfsDateTest.java
Fix issue #976
Previously, DateTimeException was raised for dates like 20219999. This
exception was not caught in RowParser:
```
private <T> T parseAsType(
...
try {
return parsingFunction.apply(s);
} catch (IllegalArgumentException | ZoneRulesException e) {
```
We prefer to change GtfsDate instead of RowParser for avoiding
complicating the generic RowParser code.
=> fix: Raise IllegalArgumentException for invalid date

.github/workflows/triage.yml
**Summary:**
This PR provides support to programmatically create a card in [bug triage board](https://github.com/MobilityData/gtfs-validator/projects/1) when a new bug is reported (i.e. an issue is labelled with [`bug`](https://github.com/MobilityData/gtfs-validator/labels/bug)).
If an issue is labelled `bug` it should be added to the board in the column "Requires investigation".
Also an automated message should appear in the issue: 
"Thank you for your reporting a bug. The issue has been placed in [triage](https://github.com/MobilityData/gtfs-validator/projects/1), the MobilityData team will follow-up on it."
- ~[ ] Run the unit tests with `gradle test` to make sure you didn't …
=> ci: bug triage

core/build.gradle, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedContainer.java, core/src/test/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedContainerTest.java
Function name was changed to getTableForFilename to make clear that it
accepts file name including ".txt" extension.
This function will be used by translations validator that must be ready
to handle invalid table names, that is why the return type is changed to
an explicit Optional.
=> feat: Return optional from getTableForFilename

core/build.gradle, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java, core/src/test/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedContainerTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsStop.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsStopTableContainer.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/StopEntityValidator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/StopFileValidator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/WholeFeedValidator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoaderTest.java
This will be used by GTFS translations validator that needs to work with
arbitrary tables.
flogger-system-backend was added to test dependencies. It is required
for testing ValidatorLoader class that initializes a static
FluentLogger.
=> feat: Support injection of the whole GtfsFeedContainer

core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableContainer.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsStopTableContainer.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/FieldNameConverter.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
These methods will be used by translations validator.
Sample code for GtfsStopTimeTableContainer.
```
private void setupIndices(NoticeContainer noticeContainer) {
for (GtfsStopTime newEntity : entities) {
CompositeKey key = new CompositeKey(newEntity.tripId(), newEntity.stopSequence());
GtfsStopTime oldEntity = byTripIdAndStopSequenceMap.getOrDefault(key, null);
if (oldEntity != null) {
noticeContainer.addValidationNotice(
new DuplicateKeyNotice(
gtfsFilename(),
newEntity.csvRowNumber(),
oldEntity.csvRowNumber(),
GtfsStopTimeTableLoader.TRIP_ID_FIELD_NAME,
oldEntity.tripId(),
GtfsStopTimeTableLoader.STOP_SEQUENCE_FIELD_NAME,
oldEntity.stopSequence()));
} else {
byTripIdAndStopSequenceMap.put(key, newEntity);
}
}
for (GtfsStopTime entity : entities) {
byTripIdMap.put(entity.tripId(), …
```
=> feat: Add byPrimaryKey and getKeyColumnNames methods to GtfsTableContainer

RULES.md, docs/NOTICES.md, main/build.gradle, main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsPathwayIsBidirectionalEnum.java, main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsPathwaySchema.java, main/src/main/java/org/mobilitydata/gtfsvalidator/util/StopUtil.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayReachableLocationValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/util/StopUtilTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/PathwayReachableLocationValidatorTest.java
Fix issue #974, issue #975
Validate that if a station has pathways, then each location is
reachable in both directions: there is a way to get to that location
from some entrance and a way to get from that location to some
entrance.
Notices are reported for platforms, boarding areas and generic nodes
but not for entrances or stations.
Notices are not reported for platforms that have boarding areas since
such platforms may not have incident pathways. Instead, notices are
reported for the boarding areas.
=> feat: Validate that locations are reachable if a station has pathways

RULES.md, docs/NOTICES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayDanglingGenericNodeValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/PathwayDanglingGenericNodeValidatorTest.java
A dangling node has just one incident location in the pathway graph.
Such generic node is useless because there is no benefit in visiting it.
=> feat: Validate that a generic node is not dangling

RULES.md, docs/NOTICES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TranslationFieldAndReferenceValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TranslationFieldAndReferenceValidatorTest.java
Checks that fields and values provided in translations are correct and checks that a
translation references existing entity.
This validator gracefully handles legacy Google translations format. If translations.txt
does not follow the new format, then no validations are performed.
=> feat: Validate field presence and key integrity for translations.txt

RULES.md, docs/NOTICES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidatorTest.java
closes #950
**Summary:**
This PR provides support to check `STATION` or `ENTRANCE` in `StopZoneIdValidator`.
No notice should be generated for a record from `stops.txt` if `stop.zone_id` is empty AND `stops.location_type=1` or `stops.location_type=2`
=> fix: StopZoneIdValidator

docs/NOTICES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/UrlConsistencyValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/UrlConsistencyValidatorTest.java
relates to #907 and #909 
**Summary:**
This PR reworks the rule logic implemented in #932: 
- a notice is generated for each stop/agency/route whose url is duplicate.
=> fix: validate route, stops and agency consistency urls

main/src/main/java/org/mobilitydata/gtfsvalidator/util/StopUtil.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/GtfsTripServiceIdForeignKeyValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/MissingLevelIdValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ParentLocationTypeValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayEndpointTypeValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ShapeToStopMatchingValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimeTravelSpeedValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/table/GtfsLevelTableLoaderTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/ParentLocationTypeValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/ShapeToStopMatchingValidatorTest.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/ForeignKeyValidatorGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java
Fix issue #1010
Any foreign key reference may be potentially broken. Authors of the
validator rules must bear that in mind and implement appropriate
behaviour.
A considered alternative is to run all foreign key checks separately -
but this is not preventing all bugs. E.g., trips.service_id is
referencing either calendar.txt or calendar_dates.txt.
```
// This may raise NPE even if all foreign key checks succeded.
calendarContainer.byServiceId(trip.serviceId())
```
=> feat: Return Optional from byXyz methods

core/src/main/java/org/mobilitydata/gtfsvalidator/util/ServicePeriod.java, core/src/test/java/org/mobilitydata/gtfsvalidator/util/ServicePeriodTest.java, main/src/main/java/org/mobilitydata/gtfsvalidator/util/CalendarUtil.java, main/src/main/java/org/mobilitydata/gtfsvalidator/util/ServiceIdIntersectionCache.java, main/src/test/java/org/mobilitydata/gtfsvalidator/util/CalendarUtilTest.java
GTFS Validator has upgraded from Java 8 to 11.
=> chore: Use LocalDate.EPOCH available in Java 11

RULES.md, docs/NOTICES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java
closes #1017 
**Summary:**
This PR provides support to upgrade `StopZoneIdValidator` to ERROR.
-`StopWithoutZoneIdNotice` :
> Conditionally Required:
> 
> - Required if providing fare information using fare_rules.txt
https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt
=> chore: upgrade StopZoneIdValidator to ERROR

RULES.md, docs/NOTICES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/LocationHasStopTimesValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java
closes #1017 
**Summary:**
This PR provides support to upgrade `LocationWithUnexpectedStopTimeNotice` to ERROR.
`LocationWithUnexpectedStopTimeNotice`:
> Referenced locations must be stops/platforms, i.e. their stops.location_type value must be 0 or empty.
https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stop_timestxt
=> chore: upgrade LocationWithUnexpectedStopTimeNotice to ERROR

RULES.md, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/EmptyColumnNameNotice.java, docs/NOTICES.md
closes #1017 
**Summary:**
This PR provides support to upgrade `EmptyColumnNameNotice` to ERROR.
`EmptyColumnNameNotice`:
> The first line of each file must contain field names.
https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#file-requirements
=> chore: upgrade EmptyColumnNameNotice to ERROR

RULES.md, docs/NOTICES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TranslationFieldAndReferenceValidator.java
closes #1026 
**Summary:**
This PR provides support to update `TranslationForeignKeyViolationNotice `: from `WARNING` to `ERROR`.
According to the [specification](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#translationstxt):
> The value in record_id must be a main ID of the table
=> chore: upgrade TranslationForeignKeyViolationNotice to ERROR

core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultFieldValidator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/DefaultFieldValidatorTest.java
**Summary:**
This PR ensures that phone number validation is skipped when country code is unknown (invalid or unprovided). Adds a unit test for this case as well.
Closes https://github.com/MobilityData/gtfs-validator/issues/1058.
**Background:**
The intent of making the country code optional in PR https://github.com/MobilityData/gtfs-validator/pull/851 was to skip phone number validation if country code wasn't provided at the command line. Apparently in the main branch phone number validation is run even when the country code is not provided or unknown. 
I'm not sure if there was a regression (perhaps in PR https://github.com/MobilityData/gtfs-validator/pull/862?) or if we just didn't have sufficient unit test coverage initially to check all cases.
In the main branch we currently have a …
=> fix: Skip phone number validation when country code is unknown

README.md, docs/USAGE.md
- Fix to README.md: feedback gathered after testing the beta release documentation
- Fix USAGE.md for the typo in the `export_notices_schema` parameter
=> docs: fix typos in README.md and USAGE.md

RULES.md, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidatorTest.java
**Summary:**
This PR provides support to avoid false positives in the context of `StopZoneIdValidator`.
The validator doesn't trigger `StopWithoutZoneIdNotice` when the fares depend on the routes.
1. Run the fix proposal on [10-15 Transit's GTFS Schedule source](https://transitfeeds.com/p/10-15-transit/936/latest/download). This file has the following structure that is considered valid:
| fare_id | route_id | origin_id | destination_id | contains_id |
|---------|----------|-----------|----------------|-------------|
| 2331    | 7468     |           |                |             |
| 2331    | 7469     |           |                |             |
| 2331    | 7925     |           |                |             |
(from …
=> fix: False positive for StopZoneIdValidator

jitpack.yml, main/build.gradle, output-comparator/build.gradle
**Summary:**
This is a fix to support build on [jitpack.io](jitpack.io)
The project should build.
See [logs](https://jitpack.io/com/github/MobilityData/gtfs-validator/502f920/build.log).
=> build: Jitpack

README.md, docs/ACCEPTANCE_TESTS.md, scripts/comment_generator.py, scripts/mobility-database-harvester/harvest_latest_versions.py
**Summary:**
The Mobility Database is now hosted on old.mobilitydatabase.org as we are moving to a new solution in the upcoming months. Since the acceptance tests are leveraging the Mobility Database, the scripts using the URL had to be updated.
Same as before.
=> fix: Updates scripts to modify mobilitydatabase.org to old.mobilitydatabase.org

.github/workflows/acceptance_test.yml, .github/workflows/docker.yml, .github/workflows/end_to_end.yml, .github/workflows/end_to_end_100.yml, .github/workflows/end_to_end_big.yml, .github/workflows/formatting.yml, .github/workflows/test_pack_doc.yml
**Summary:**
https://github.com/actions/setup-java#supported-distributions says:
>NOTE: Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from adopt to temurin to keep receiving software and security updates. See more details in the [Good-bye AdoptOpenJDK post](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).)
This PR changes GitHub Actions to use temurin instead of adopt as highly recommended above.
It also updates acceptance_test to use `actions/setup-java@v2` instead of `actions/setup-java@v1` to be consistent with the other GitHub Actions.
Use temurin Java distribution on CI instead of adopt, use `actions/setup-java@v2` consistently.
Please make sure these boxes are …
=> ci: Change Java distribution adopt->temurin

docs/BUILD.md
**Summary:**
Gradle commands `shadowJar` and `aggregateJavadocs` are currently missing from the build docs. Currently you have to hunt through the GitHub Action CI code to find them.
This PR adds them to the build docs to make them more obvious.
I should be able to read the build docs and understand all the key Gradle tasks that help me to build and run the project.
=> docs: Add gradle commands shadowJar and aggregateJavadocs

.github/workflows/end_to_end.yml, .github/workflows/end_to_end_100.yml, .github/workflows/end_to_end_big.yml
Per discussion in issue #1129, I think I ran into an edge-case where there are multiple jars in the main/build/libs directory (maybe from a previous build?) that caused the script to fail.  Attempting to fix by being more specific about which of the :main project jars to use (hint: we want the shadow jar).
=> fix: Modify end_to_end.yml to be more specific about which gtfs-validator jar is used

docs/NOTICES.md
**Summary:**
The table in `NOTICES.md` was showing more values than what the notice produced. 
**Expected behaviour:** 
Only the file name is produced by this notice, as seen in the `MissingRequiredFileNotice.java` file:
```
public class MissingRequiredFileNotice extends ValidationNotice {
private final String filename;
public MissingRequiredFileNotice(String filename) {
super(SeverityLevel.ERROR);
this.filename = filename;
}
}
```
~~- [ ] Run the unit tests with `gradle test` to make sure you didn't break anything~~
=> Docs: fix typo for Missing RequiredFileNotice

.github/workflows/acceptance_test.yml
closes https://github.com/MobilityData/gtfs-validator/issues/1094
**Summary:**
This PR removes the usage of GCP cloud storage. The content of this PR fixes the behavior described [here](https://github.com/MobilityData/gtfs-validator/issues/1094)
On forks, acceptance tests should run and not fail because of missing credentials: upload to cloud storage is not used - on this GitHub repository, google cloud storage is used as a backup. 
=> ci: Remove upload of validation reports to Google Cloud

docs/BUILD.md
**Summary:**
The `$` isn't actually part of the command you need to execute. 
IMHO the docs are better without it because it makes it easier to copy/paste if you're familiar with running things from the command line, and is less confusing if you're not as you'll get an error if you include the dollar sign in the command.
Docs for commands should include exact commands that can be copy/paste into command line and execute.
=> docs: Remove dollar sign from commands

.github/workflows/test_pack_doc.yml, app/gui/build.gradle, app/gui/src/main/java/org/mobilitydata/gtfsvalidator/app/gui/Main.java, app/gui/src/main/resources/logging.properties, app/pkg/build.gradle, app/pkg/src/main/java/module-info.java, app/pkg/src/main/java/org/mobilitydata/gtfsvalidator/app/pkg/Main.java, build.gradle, core/build.gradle, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeSchemaGenerator.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java, docs/ARCHITECTURE.md, docs/BUILD.md, settings.gradle
**Summary:**
Introduces functionality to package the GTFS Validator as an installable application, including a bundled JRE, to make it easier for users to run the validator.  As discussed in issue #1112, https://bit.ly/gtfs-validator-packaged-exe, and #1124.
Note: This is an initial draft review to get agreement on package structure before additional follow-up work.
Prerequisites:
* A Windows or Mac OS build machine (I haven't tested on Linux, but it should theoretically work there as well)
* A Java SDK that includes `jlink` and `jpackage`
* If building on Windows, have https://wixtoolset.org/ installed on your path for Windows Installer support
To package:
* run `./gradlew jpackage`
Expected:
* You should find a "GTFS Validator" application and installer in the …
=> feat: Packaged Executable

output-comparator/build.gradle
**Summary:**
This PR:
- removes System Lambda from `build.gradle`
- updates the implementation of SystemStubs to be a `testImplementation`
- updates the version of SystemStubs
Same as before, but the dependency to SystemStubs won't be packaged in the JAR file.
=> fix: SystemStubs test dependency

.github/workflows/test_pack_doc.yml
**Summary:**
I believe ubuntu-20.04 was originally added to troubleshoot issues discussed in PR https://github.com/MobilityData/gtfs-validator/pull/1086, which have since been resolved.
Given that:
* we have a lot of CI tests running, which makes review of the CI tests challenging (see https://github.com/MobilityData/gtfs-validator/issues/1095)
* these seem to be redundant given that we're also running on `ubuntu-latest`
...I'm proposing that we remove running on this specific version of ubuntu. 
This should remove 6 redundant checks (3 occurrences x 2 for each Java version 11 and 17) and will also reduce the amount of time required for all CI checks to complete.
Don't run redundant CI tests.
Please make sure these boxes are checked before submitting your pull …
=> ci: Remove ubuntu-20.04 from CI

.github/workflows/docker.yml
Fixes #1105 : Docker builds are failing
This PR replaces the Personal Access Token (PAT) used in the `docker.yml` workflow with a GitHub Token. [According to GitHub](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#authenticating-to-the-container-registry), PATs used to authenticate to `ghcr.io` should be avoided. 
Along with the changes made in this PR, the steps shown [here](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio) were followed so that the package could access the GitHub token.
The Docker Image push to GitHub …
=> fix: Docker Image push to GitHub Container Registry

app/gui/src/main/java/org/mobilitydata/gtfsvalidator/app/gui/MonitoredValidationRunner.java, app/gui/src/main/java/org/mobilitydata/gtfsvalidator/app/gui/ValidationDisplay.java, main/src/test/java/org/mobilitydata/gtfsvalidator/report/model/ReportSummaryTest.java
Per discussion in #1146, I am cleaning up a few "import package.*" wildcard imports in the codebase.
=> fix: Replace Java wildcard imports with explicit imports.

.github/workflows/package_app.yml, .github/workflows/package_installers.yml
Implementation for a GitHub workflow to build the GUI application installers and packages on all key environments.
=> feat: Initial entry for a workflow to package the gui application.

app/gui/src/main/java/org/mobilitydata/gtfsvalidator/app/gui/GtfsValidatorApp.java, app/gui/src/main/java/org/mobilitydata/gtfsvalidator/app/gui/GtfsValidatorPreferences.java, app/gui/src/main/java/org/mobilitydata/gtfsvalidator/app/gui/Main.java, app/gui/src/test/java/org/mobilitydata/gtfsvalidator/app/gui/GtfsValidatorAppTest.java, app/gui/src/test/java/org/mobilitydata/gtfsvalidator/app/gui/GtfsValidatorPreferencesTest.java, app/pkg/build.gradle
Currently, the GUI app does not remember settings (input and output paths, advanced settings) between different executions of the app.   This PR adds support for persisting settings between runs of the validator, using the Java Preferences API for storage.
Closes #1165.
=> feat: Persist GUI app settings between executions

RULES.md
**Summary:**
This PR fixes 2 titles that were incorrectly displayed in RULES.md. In both cases, the problem was caused by the absence of between a tag and the title, for example:
```
</details>
```
should be 
```
</details>
```
Same as before with properly formatted titles.
=> fix: Fixes titles in RULES.md

app/pkg/build.gradle, main/src/main/java/org/mobilitydata/gtfsvalidator/util/VersionResolver.java
See discussion in #1181.  Basically, the packaged app uses Java Modules, which requires explicit listing of all JRE dependencies.  `jdeps` picks up most of them, but we have a hidden dependency on the JRE's crypto functionality in order to pull https:// urls.  This manifested as an exception when querying the current app version from https://raw.githubusercontent.com but it also repros if you attempt to download an https:// feed.
Closes #1181.
=> fix: Bug with ssl network connections + Java module permissions.

core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/FieldLevelEnum.java, core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/Recommended.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableContainer.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableLoader.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsStopTableContainer.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/Analyser.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/GtfsFieldDescriptor.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/GtfsFileDescriptor.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
**Summary:**
Related to issue #885
Adds a new annotation for recommended fields
Provides additional functionality around the `recommended` annotation. It can now be applied to fields. 
~- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)~
@isabelle-dr per [your request](https://github.com/MobilityData/gtfs-validator/pull/1123#pullrequestreview-958240912), this pull request contains just the annotation. I don't think a screenshot makes sense in this scenario.
=> feat: recommended annotation

.github/workflows/package_installers.yml, app/pkg/build.gradle
Per #1183, I'm investigating the corruption of `dmg` package on MacOS for the packaged app.  This PR introduces a temporary fix to unsign the app via the GitHub `package_installers.yml` workflow.  A more permanent fix will be to actually sign the app.
=> fix: Temporary fix for MacOS validator app corruption

.gitignore
**Summary:**
Summarize the changes in the pull request including how it relates to any issues (include the #number, or link them).
Resolves #1195 
When building the solution locally, the `main/bin` folder is  generated. This should be ignored by source control. 
=> chore: add bin folder to .gitignore

RULES.md, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/MissingRecommendedFileNotice.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainerTest.java, main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedInfoSchema.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
**Summary:**
Resolves #877 
Adds a new annotation for recommended files and applies this annotation to `feed_info.txt` ~and `shapes.txt`~.
A new validator warning is generated when either `feed_info.txt` is missing
Here is the sample output from the validator for a data set with missing `feed_info.txt`:
```json
{
"notices": [
{
"code": "missing_recommended_file",
"severity": "WARNING",
"totalNotices": 1,
"sampleNotices": [
{
"filename": "feed_info.txt"
}
]
}
]}
```
=> feat: apply recommended file notice to feed_info

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/MissingRecommendedFieldNotice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java
**Summary:**
Related #885
Adds the recommended field notice.
~- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)~
=> feat: add recommended field notice

.dockerignore, .github/workflows/docker.yml, Dockerfile, README.md
**Summary:**
As a new contributor wanting to try building/running PR branches locally, I was surprised that the `Dockerfile` didn't actually build the application but rather relied on it being built first by a toolchain on the host machine. The intent of `Dockerfile` is usually to capture and pin the build dependencies as well as runtime environment.
`docker build .` always goes from branch source to ready-to-run container image
**Proposal:**
Ideally `Dockerfile` handles a full build from source. I also configured the default entrypoint to handle running the CLI, as the instructions indicated running the Docker container would give you a shell you could run the jar on but you'd need to override the entrypoint to `sh` to get that rather than the jShell the JDK base …
=> feat(ci): handle gradle build in Dockerfile

.github/config.yml
Tiny fixes to the welcome bot messages.
=> Fix: Update config.yml

README.md
**Summary:**
This adds an example validation report in the project's README. 
When the user clicks on the link, an example of the validation report appears.
=> docs: Add example of validation report

scripts/queue_runner.sh
**Summary:**
Per issue #1226, I'd like to try bumping the max heap size for the validator in the acceptance test queue_runner.sh script to see if it helps with test cancellations.
=> fix: Bump queue_runner.sh max heap size to 10Gb

main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTransferSchema.java
**Summary:**
Summarize the changes in the pull request including how it relates to any issues (include the #number, or link them).
Resolves #1113
This PR expands @bdferris-v2  's efforts and applies the multiple @PrimaryKey functionality to the remaining schema's defined in #1113. 
~~Marking as draft until #1190 is merged.~~
I've tested this functionality with a hand edited GTFS data set that can be shared if helpful.
=> feat: Apply multiple @PrimaryKey annotations to Transfers 

.dockerignore, .github/workflows/docker.yml, Dockerfile, cli/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java
The current `:latest` Docker container build of the `master` branch is broken due to changes in #1229:
```console
$ docker pull ghcr.io/mobilitydata/gtfs-validator:latest
latest: Pulling from mobilitydata/gtfs-validator
1efc276f4ff9: Already exists 
a2f2f93da482: Already exists 
12cca292b13c: Already exists 
69e15dccd787: Already exists 
4f4fb700ef54: Already exists 
Digest: sha256:b796fee1fc8e99d857ab1fd6f6438af7d20c3dba74af4d1934f609c22e4dc1ac
Status: Downloaded newer image for ghcr.io/mobilitydata/gtfs-validator:latest
ghcr.io/mobilitydata/gtfs-validator:latest
$ docker run --rm ghcr.io/mobilitydata/gtfs-validator:latest --help
Error: Unable to access jarfile gtfs-validator-cli.jar
```
I've made the following changes in this PR to both fix the issue and add a testing step that would …
=> fix(docker): update path to CLI jar

docs/CONTRIBUTING.md
=> fix(docs): remove duplicate prefix in example commits

.github/workflows/package_installers.yml, app/pkg/build.gradle, app/pkg/src/main/mac-resources/entitlements.plist
**Summary:**
As tracked in #1200, this PR adds support for code-signing and notarizing the MacOS app.  This will mean the user no longer has to ⌘-click the app to open it the first time.  Note that they will still get the following warning when running the app for the first time:
But they can just click "Ok" and the app will run.  I don't think there is any way to avoid that dialog without distributing the app through the Mac App Store.
Closing #1200.
=> fix: Sign and Notarize MacOS App

core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/CurrencyAmount.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/InvalidCurrencyAmountNotice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/testing/LoadingHelper.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java, main/src/main/java/org/mobilitydata/gtfsvalidator/runner/ValidationRunner.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/Analyser.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/CurrencyAmountValidatorGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/GtfsAnnotationProcessor.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/GtfsFieldDescriptor.java, processor/tests/src/main/java/org/mobilitydata/gtfsvalidator/processor/tests/CurrencyAmountSchema.java, processor/tests/src/test/java/org/mobilitydata/gtfsvalidator/processor/tests/CurrencyAmountSchemaTest.java
This will be used for various fields in the Fares V2 spec to reduce duplicate validation logic.  Specifically, I will use this functionality in PR #1228 but I'm splitting it out to simplify the review.
=> feat: Add @CurrencyAmount annotation for currency amount validation

core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/GtfsValidatorAnnotationTest.java
Closes #1262
Add a unit-test that checks that any subclass of SingleEntityValidator or FileValidator is also annotated with @GtfsValidator.
=> feat: Check validator subclasses are annotated with @GtfsValidator

cli/src/main/java/org/mobilitydata/gtfsvalidator/cli/Arguments.java, cli/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java, cli/src/test/java/org/mobilitydata/gtfsvalidator/cli/ArgumentsTest.java
**Summary:**
Per discussion in #1256: refactor command-line argument parsing for clarity. Do not exit with non-zero exit code when exporting notices schema.
=> fix: Do not return non-zero exit code when exporting schema via CLI.

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/AgencyConsistencyValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/GtfsTripServiceIdForeignKeyValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/MissingTripEdgeValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayEndpointTypeValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimeArrivalAndDepartureTimeValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TimepointTimeValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TransferDirection.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TransfersInSeatTransferTypeValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TranslationFieldAndReferenceValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TripAgencyIdValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TimepointTimeValidatorTest.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/CurrencyAmountValidatorGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/EndRangeValidatorGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/EntityImplementationGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/LatLonValidatorGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerIndexGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
E.g., now use `GtfsStop.STOP_ID_FIELD_NAME` instead of `GtfsStopTableLoader.STOP_ID_FIELD_NAME`.
Motivation
1. Table loader classes should be only used for loading data tables. They should not be used by validator classes.
2. Our final goal is to stop generating table loader classes and instead make them usual classes that use a GTFS schema as a parameter. GTFS field names have to be generated, so we move them to entity classes that are generated anyway.
=> Move GTFS field names from table loader to entity classes

core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, processor/build.gradle, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/EntityImplementationGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/EnumGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/GtfsAnnotationProcessor.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java, processor/src/test/java/org/mobilitydata/gtfsvalidator/processor/EnumGeneratorTest.java, processor/tests/src/main/java/org/mobilitydata/gtfsvalidator/processor/tests/ByteGtfsEnum.java, processor/tests/src/main/java/org/mobilitydata/gtfsvalidator/processor/tests/EnumSizesSchema.java, processor/tests/src/main/java/org/mobilitydata/gtfsvalidator/processor/tests/IntGtfsEnum.java, processor/tests/src/main/java/org/mobilitydata/gtfsvalidator/processor/tests/ManyFieldsSchema.java, processor/tests/src/main/java/org/mobilitydata/gtfsvalidator/processor/tests/ShortGtfsEnum.java, processor/tests/src/test/java/org/mobilitydata/gtfsvalidator/processor/tests/EnumSizesSchemaTest.java, processor/tests/src/test/java/org/mobilitydata/gtfsvalidator/processor/tests/ManyFieldsSchemaTest.java
GTFS enums usually fit into one byte, so we don't need an int. GTFS tables usually less than 16 fields, so we need a byte or a short int for storing a bitmask of assigned fields.
Smaller fields allow us to save memory for the largest table - stop_times.txt that may have 30 M lines.
Instead of:
```
class GtfsStopTime {
// ...
private int pickupType;
private int dropOffType;
private int continuousPickup;
private int continuousDropOff;
private int timepoint;
private int bitField0_;
}
```
we have now:
```
class GtfsStopTime {
// ...
private byte pickupType;
private byte dropOffType;
private byte continuousPickup;
private byte continuousDropOff;
private byte timepoint;
private short bitField0_;
}
```
which is 5 * (4 - 1) + 2 = 17 bytes smaller. Java aligns classes by 8 bytes, so we actually …
=> Use smaller integer field types for GTFS entity classes

.github/workflows/acceptance_test.yml, .github/workflows/docker.yml, .github/workflows/end_to_end.yml, .github/workflows/formatting.yml, .github/workflows/package_installers.yml, .github/workflows/test_pack_doc.yml, .github/workflows/triage.yml
Per discussion in https://github.com/MobilityData/gtfs-validator/issues/1269.
This updates the version for most actions where appropriate.  For `eskatos/gradle-command-action`, we migrate to the now official `gradle/gradle-build-action`.  There is no upgraded version of `gradle/wrapper-validation-action` available yet (see gradle/wrapper-validation-action#66 for discussion) but this change already reduces the warning volume significantly.
=> bug: upgrade GitHub Workflow actions to Node16 compatible versions

core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java
**Summary:**
Don't ignore invalid language codes in RowParser.asLanguageCode. Locale::forLanguageTag ignores invalid language codes and no notices are created. 
Invalid language detected
=> fix: Don't ignore invalid language codes in RowParser.asLanguageCode

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableRegistryGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/ValidatorRegistryGenerator.java
Unchecked conversion is usually a Java warning but users of GTFS Validator may upgrade it to a compilation error.
=> Avoid unchecked conversion in table and validator registries

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerIndexGenerator.java, processor/tests/src/main/java/org/mobilitydata/gtfsvalidator/processor/tests/MultiColumnUnsupportedTranslationsPrimaryKeySchema.java, processor/tests/src/test/java/org/mobilitydata/gtfsvalidator/processor/tests/MultiColumnUnsupportedTranslationsPrimaryKeySchemaTest.java
The `@PrimaryKey(translationRecordIdType)` field is used to indicated which keys, if any, for a given GTFS entity can be used for performing `translations.txt` lookups via `byTranslationKey()` methods generated in the table container.  Currently, code in `TableContainerIndexGenerator` will generate an implementation for `byTranslationKey()` even if none of the @PrimaryKey fields have been marked as the translation RECORD_ID.  This can lead to some weird behavior where the method will return a value even if none should be returned or generate code that does not actually compile.
This PR fixes this behavior by no longer generating a `byTranslationKey()` implementation if the entity type does not support.  Instead, empty is returned.
Please make sure these boxes are checked before submitting …
=> fix: byTranslationKey() for multi-key schemas without translations.txt support

processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerIndexGenerator.java
The generated code may be analysed by engineers, so it should be readable.
Example of the new code.
```
CompositeKey key = CompositeKey.builder()
.setFromStopId(newEntity.fromStopId())
.setToStopId(newEntity.toStopId())
.setFromTripId(newEntity.fromTripId())
.setToTripId(newEntity.toTripId())
.setFromRouteId(newEntity.fromRouteId())
.setToRouteId(newEntity.toRouteId())
.build();
```
=> Initialize one field per line in the generated code

.github/workflows/acceptance_test.yml, .github/workflows/end_to_end.yml
We want to avoid running out of heap memory when processing large feeds.
Closes #1304.
=> fix: Bump validation workflows to use large machine instances

RULES.md, core/src/main/java/org/mobilitydata/gtfsvalidator/model/NoticeReport.java
**Summary:**
Closes #1322 
~~When either `feed_expiration_date7_days` or `feed_expiration_date30_days` is triggered, the link in the HTML report isn't broken. ~~
EDIT: the notice name in the validation report is the same than the notice name in RULES.md for these two notices.
=> Docs: Fix RULES.md notice name for 2 notices

.github/workflows/triage.yml
**Summary:**
Attempt to fix the bug triage workflow, which is broken. Related issue: #1298 
This solution came from this thread: https://github.com/alex-page/github-project-automation-plus/issues/81
When an issue is opened with a "bug" label, the workflow runs properly and a card is added to the repo project "Bug triage".
=> Fix: Fix bug triage workflow

.github/workflows/test_pack_doc.yml, RULES.md, cli/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/Notice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeSchemaGenerator.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ClassGraphDiscovery.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeSchemaGeneratorTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/ClassGraphDiscoveryTest.java, main/build.gradle, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/NoticeDocumentationTest.java
**Summary:**
When writing new validation rules, we often forget to update `RULES.md` with updated documentation.  While #1324 has some ideas on addressing that in the long term, in the short term, we can add a unit-test that will fail if there is an entry in `RULES.md` for a newly added notice.
For example, this test should fail initially because `StopWithoutLocationNotice` is missing from `RULES.md` per #1330.
=> feat: Add unit test to verify that every Notice has an entry in RULES.md

RULES.md
**Summary:**
Tests were failing due to poorly named anchor tag
`<a name="MissingStopName"/>`
should have been
`<a name="MissingStopNameNotice"/>`
Also updated whitespace formatting issues.
MissingStopNameNotice should be properly documented and found by tests.
=> Fix whitespace and anchor tag

RULES.md, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/InvalidCurrencyAmountNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopNameValidator.java
Specifically, this PR updates `RULES.md` to:
* Fix incorrectly named fields: docs should match underlying field names in Java source / JSON schema
* Add missing fields: docs should contain all fields from Java source / JSON schema
* Fix inconsistent formatting
* Fix two incorrectly-named fields in the Java source
This is an intermediate PR that brings us one step closer to alignment and generation of Notice documentation from the source code itself per #1324.
=> fix: Inconsistencies in RULES.md against underlying source

core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/Required.java, core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/RequiredColumn.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/AnyTableLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsColumnDescriptor.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultTableHeaderValidator.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/TableHeaderValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTransferSchema.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/Analyser.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/GtfsFieldDescriptor.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableDescriptorGenerator.java, processor/tests/src/main/java/org/mobilitydata/gtfsvalidator/processor/tests/RequiredAnnotationSchema.java, processor/tests/src/main/java/org/mobilitydata/gtfsvalidator/processor/tests/RequiredColumnAnnotationSchema.java, processor/tests/src/test/java/org/mobilitydata/gtfsvalidator/processor/tests/RequiredAnnotationSchemaTest.java, processor/tests/src/test/java/org/mobilitydata/gtfsvalidator/processor/tests/RequiredColumnAnnotationSchemaTest.java
**Summary:**
Closes #1198. Added a new annotation `@RequiredColumn` to allow for scenario where a column must exist in the file, but values for that column may be empty.
It may be useful in the future to separate the existing `@Required` annotation into `@RequiredFile` and `@RequiredValue` annotations. I've opened #1343 for discussion of that topic.
Given the following `transfers.txt` file, the following should not throw an error:
```
from_stop_id,to_stop_id,transfer_type,min_transfer_time
1,2,,
```
This is a valid use case [according to the spec](https://gtfs.org/schedule/reference/#:~:text=recommended%20transfer%20point%20between%20routes) in that the transfer_type value is empty which indicates a "Recommended transfer point between routes".
Please make sure …
=> Fix 1198: separate required column from required value

main/src/main/java/org/mobilitydata/gtfsvalidator/util/TripCalendarUtil.java, main/src/test/java/org/mobilitydata/gtfsvalidator/util/TripCalendarUtilTest.java
Adds `TripCalendarUtil`, which provides methods for computing service coverage windows based on daily trip counts. 
Will hopefully be useful for #886 and PR #1289.
=> feat: Add code for computing service coverage windows and trip counts

RULES.md, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/MixedCaseRecommendedFieldNotice.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/MixedCaseValidatorGenerator.java, processor/tests/src/test/java/org/mobilitydata/gtfsvalidator/processor/tests/MixedCaseSchemaTest.java
**Summary:**
Closes #1392
Add field value to notice.  Note, does not change casing of `filename` field as everywhere else is using the lowercase version.  
Should show the offending value.
=> fix: add field value to mixed case notice

README.md, web/client/README.md
**Summary:**
This is part of the pre-release tasks. This PR adds the GTFS Web validator information to the project root's README file.
The GTFS Web Validator information is in the project root's  README file and linking web client and service sub-packages README for more information.
=> chore: add web validator information to README

.github/workflows/acceptance_test.yml, .github/workflows/end_to_end.yml
**Summary:**
The acceptance and E2E tests are time and cost-consuming workflows. As web projects have no impact on the validator's core implementation, we can ignore them in the mentioned test workflows. Web projects run their own independent set of tests.
When changes are pushed from `web` projects, the acceptance and E2E tests should not run.
=> chore: ignore web packages on acceptance and e2e tests

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/IOError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/MixedCaseRecommendedFieldNotice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/RuntimeExceptionInLoaderError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/RuntimeExceptionInValidatorError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/ThreadExecutionError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/URISyntaxError.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/AgencyConsistencyValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/DateTripsValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/DuplicateFareMediaValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ExpiredCalendarValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/FareTransferRuleDurationLimitTypeValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/FareTransferRuleTransferCountValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/FeedExpirationDateValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/LocationHasStopTimesValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/LocationTypeSingleEntityValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayEndpointTypeValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/RouteNameValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ShapeIncreasingDistanceValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ShapeToStopMatchingValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopNameValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimeArrivalAndDepartureTimeValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimeTravelSpeedValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TimepointTimeValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TransfersTripReferenceValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TranslationFieldAndReferenceValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/UrlConsistencyValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/NoticeAnnotationTest.java
This adds a new `NoticeAnnotationTest` to make sure each validation notice is annotated with @GtfsValidationNotice.  It also adds @GtfsValidationNotices to a number of notices that I missed in the first pass:
* SystemErrors
* Files with more than one child Notice class (my script only caught the first notice in the file)
=> feat: Add unit-test check for @GtfsValidationNotice annotation and notices that I missed

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/schema/NoticeSchemaGenerator.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/schema/ReferencesSchema.java, core/src/test/resources/org/mobilitydata/gtfsvalidator/notice/schema/NoticeSchemaGeneratorTest-generateJsonSchemaForNotice_duplicateKeyNotice.json, model/src/main/java/org/mobilitydata/gtfsvalidator/annotation/GtfsValidationNotice.java
PR #1366 added section references to @GtfsValidationNotice.  This PR updates the notice schema export to include them as well.  Continued work on issue #1324 
=> feat: Include section references in the notice output schema.

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/schema/NoticeSchemaGenerator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ExpiredCalendarValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/FeedExpirationDateValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayLoopValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/NoticeDocumentationTest.java
As part of automated Notice documentation extraction (#1324), this PR adds a unit-test to enforce that each Notice has a Javadoc documentation header.
=> feat: Add Notice documentation header check.

build.gradle
Per issue #1431, this PR switches us away from the Javadoc jar-based aggregation step since, best I can tell, no one is using the `jar` output (only the uncompressed Javadoc content itself) and the `jar` step is currently hanging gradle.
=> Fix: Switch javadoc aggregation plugin to non-jar version.

model/build.gradle, model/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeDocComments.java
I accidentally included the wrong @Nullable annotation on a new class (used `org.jetbrains.annotations.Nullable` when I should have used `javax.annotation.Nullable`).  We should be consistent with the rest of the codebase.
=> fix: Use correct import for @Nullable annotation.

.gitignore, web/service/build.gradle, web/service/gradle.properties, web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/Main.java, web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/controller/ValidationController.java, web/service/src/main/resources/application.properties, web/service/src/test/resources/sentry.properties
**Summary:**
Upgrade to use the spring-boot + logback framework integration from Sentry to provide better error capture.
=> feat: use sentry spring-boot

main/src/main/resources/report.html
This fixes a bug introduced in #1363 when metadata was added to the validation HTML report.  The `metadata` data structure can be null when a system error occurs when processing a feed, which ultimately results in a NPE when generating the HTML report.
=> fix: Bug in HTML report generation where feed metadata can be null

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/schema/NoticeSchema.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/schema/NoticeSchemaGenerator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/schema/NoticeSchemaGeneratorTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/testnotices/DocumentedNotice.java, core/src/test/resources/org/mobilitydata/gtfsvalidator/notice/schema/NoticeSchemaGeneratorTest-generateJsonSchemaForNotice_duplicateKeyNotice.json, core/src/test/resources/org/mobilitydata/gtfsvalidator/notice/testnotices/DocumentedNotice-DocComments.json, main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/NoticeView.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/NoticeDocumentationTest.java, model/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeDocComments.java, processor/notices/src/main/java/org/mobilitydata/gtfsvalidator/processor/notices/CommentCleaner.java, processor/notices/src/main/java/org/mobilitydata/gtfsvalidator/processor/notices/NoticeDocCommentsFactory.java, processor/notices/src/test/java/org/mobilitydata/gtfsvalidator/processor/notices/CommentCleanerTest.java, processor/notices/tests/src/test/java/org/mobilitydata/gtfsvalidator/processor/notices/CommentedNoticeTest.java
This is a usability tweak on the notice documentation support that was implemented in #1324.
We enforce that notice doc comments have the following form:
```
/**
* Short text describing the notice in a single line (required).
*
* Additional text further describing the notice on new lines (optional).
*/
```
We represented that internally as a single combined comment string, but there are uses where we'd like to split out the short summary string and the additional optional documentation so that they can be used and rendered separately, where appropriate.  This PR implements that split.
=> feat: Split the notice doc comment into a short summary string and additional documentation.

main/src/main/resources/report.html
**Summary:**
Closes #1454. Some CSS was accidentally removed in #1447, disabling the accordian feature in the report.
Notice details should load collapsed, and be expandable and collapsible (accordian). 
=> Fix: Restore missing CSS

core/src/main/java/org/mobilitydata/gtfsvalidator/table/AnyTableLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableDescriptor.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsTestTableDescriptor.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableDescriptorGenerator.java
Closes #1461.
In PR #1228 I added support for @GtfsTable.maxCharsPerColumn to support files with especially large column values. Unfortunately, this feature was accidentally removed in PR #1284.  This PR adds it back.
=> fix: Add back support for @GtfsTable.maxCharsPerColumn.

main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java
**Summary:**
[Add a "Route Names" GTFS Component #1464](https://github.com/MobilityData/gtfs-validator/issues/1464)
Closes #1464 
"Route Names" component should be added to this list. We consider this component present if both the fields route_short_name and route_long_name in routes.txt are present, and if they have at least one value defined.
=> feat: Added route names component

processor/notices/src/main/java/org/mobilitydata/gtfsvalidator/processor/notices/CommentCleaner.java, processor/notices/src/test/java/org/mobilitydata/gtfsvalidator/processor/notices/CommentCleanerTest.java
Closes #1478.
There is a bug in extracting `NoticeDocumentation.shortSummary` strings from Notice comment blocks.  Specifically, it's not correctly handling longer short-summary strings.  This PR adds a fix.
=> Fix: bug in Notice documentation comment splitting.

core/src/main/java/org/mobilitydata/gtfsvalidator/io/ValidationReportDeserializer.java, core/src/main/java/org/mobilitydata/gtfsvalidator/model/NoticeReport.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/Notice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainer.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/ResolvedNotice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/SystemError.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/ValidationNotice.java, core/src/test/java/org/mobilitydata/gtfsvalidator/model/NoticeReportTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeContainerTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/NoticeTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/ResolvedNoticeTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/testnotices/DoubleFieldNotice.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/testnotices/GtfsTypesValidationNotice.java, core/src/test/java/org/mobilitydata/gtfsvalidator/notice/testnotices/StringFieldNotice.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/table/AnyTableLoaderTest.java, main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/NoticeView.java, main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/ReportSummary.java, main/src/test/java/org/mobilitydata/gtfsvalidator/report/model/NoticeViewTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/AgencyConsistencyValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/ShapeToStopMatchingValidatorTest.java, output-comparator/src/test/java/org/mobilitydata/gtfsvalidator/outputcomparator/cli/MainTest.java, output-comparator/src/test/java/org/mobilitydata/gtfsvalidator/outputcomparator/io/NoticeSetTest.java
As originally discussed in https://bit.ly/gtfs-validator-notice-documentation, when we introduced @GtfsValidationNotice to document validation notice, the plan was to follow-up by refactoring SeverityLevel from the notice constructor. This PR performs that refactor.
Specifically, it pulls `severityLevel` out of `Notice` and moves it to a new `ResolvedNotice` class, which is a wrapper around  `Notice` object that includes the resolved severity level.  Additionally, the severity level of the notice is resolved when it is added to `NoticeContainer`, which has been refactored to hold `ResolvedNotices` now.  This paves the way for config-driven severity levels for notices, which could be implemented within `NoticeContainer` in the future.
Closes #1472.
Please make sure these boxes are checked …
=> feat: Resolve notice severity level from @GtfsValidationNotice annotation.

web/client/src/routes/+page.svelte
**Summary:**
Fix for bug [#1440](https://github.com/MobilityData/gtfs-validator/issues/1440): Web validator allows non-zip files to be uploaded
The result should be the same as when the Validate button is clicked when no file was selected. A message should say Please include a file to validate.
=> fix: Web validator allows non-zip files to be uploaded #1440

.github/workflows/web_client_test.yml
Minor change to promote consistency. This also highlights that maybe this workflow could/should be merged into `.github/workflows/web_client_pr.yml` if we're factoring workflows more around lifecycle stage than outcome
=> refactor(ci): rename cypress workflow to be consistent

main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java, main/src/test/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadataTest.java
Close #1465 
wrote logic and unit tests for Adding a "Route Colors" component - it's present if both the fields route_color and route_text_color in routes.txt are present, and if they have at least one value defined.
=> feat: 1465 add a route colors gtfs component

main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsStopSchema.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/MixedCaseValidatorGenerator.java, processor/tests/src/test/java/org/mobilitydata/gtfsvalidator/processor/tests/MixedCaseSchemaTest.java
**Summary:**
Should close #1402.  False positives when warning for Mixed Case values such as when numbers and letters are mixed. 
Values with a letter and numbers such as `A102` `302-B` and those with only numbers like `321` should not trigger a warning.
=> fix: Mixed Case false positives

core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java, core/src/test/java/org/mobilitydata/gtfsvalidator/parsing/RowParserTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsTestTableDescriptor.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableDescriptorGenerator.java
**Summary:**
Closes #1425 
User can see the fieldName header displayed for feed_contact_email and feed_contact_url as shown in the screenshot.
=> feat: 1425 output fieldname of missing recommended field notice even if there is no column

main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/NoticeView.java, main/src/main/resources/report.html
**Summary:**
The GTFS Component now has a description to help the user understand its value.
The summary section is as wide as the compliance report.
Closes #1505 
Closes #1467 
Also fixes missing summary section for notices and missing description for the notice's fields.
Before:
With the changes:
=> feat: Provide an explanation to users about what a GTFS Component is #1505

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ExpiredCalendarValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/ExpiredCalendarValidatorTest.java
**Summary:**
Fix ExpiredCalendarValidator throwing NoSuchElementException when checking a calendar with no days set to 1.
Checking a calendar.txt file where a row has no days set to 1 does not crash the validator.
=> fix: don't throw exception on calendar with no days

.github/workflows/package_installers.yml
Forced java version to 17.0.7 in Github action package_installers.yml because the action fails with latest version which is currently 17.0.8
**Summary:**
This is a workaround until we understands what's going on with java 17.0.8-zulu
The github action should run without error
=> fix: Forced java version to 17.0.7 in github action 

docs/CONTRIBUTING.md
Include MobilityData's new developers on our core developers list now that they're onboarded. 🎉
=> docs: Update core developers list

README.md
**Summary:**
While the former link provided only a 404 page, now one gets to the MobilityData site
When I click the link in the Readme.md I get to the Homepage of MobilityData
I did not run any unit tests or the like, as it is just a link in the Readme.md
=> docs: Fix Link in README.md

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimeIncreasingDistanceValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopTimeIncreasingDistanceValidatorTest.java
**Summary:**
Added `stop_id` after `trip_id` in the notice details of `decreasing_or_equal_stop_time_distance`. 
Closes #1547 
The `stop_id` field is included in the notice details.
=> feat: add stop_id to the decreasing_or_equal_stop_time_distance notice

.github/workflows/triage.yml
The error message is saying that there is an unexpected symbol, a parenthesis, in the expression github.event.issue.labels.contains('bug'). The correct syntax for this expression is github.event.issue.labels.contains("bug").
=> Small fix, required double-quotes

.github/workflows/package_installers.yml
**Summary:**
As described in #1567, the Github actions associated with the MacOS certificate imports, notarization, and stapling were dependent on open-source projects that are not available anymore. This PR implements the MacOS certificate imports, notarization, and stapling using XCode terminal commands.
Fixes #1567
GTFS Validator App is signed and notarized.
=> fix: Package installers CI step failing 

core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedContainer.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableContainer.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTableDescriptor.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsTestTableContainer.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsTestTableDescriptor.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/DateTripsValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/ExpiredCalendarValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/MatchingFeedAndAgencyLangValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/MissingCalendarAndCalendarDateValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TimepointTimeValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TranslationFieldAndReferenceValidatorTest.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableContainerGenerator.java, processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableDescriptorGenerator.java
Per discussion in #1564, I'm looking to add base API support for changing the "required" status of some GTFS files/tables at run-time, as opposed to compile time.  This PR achieves that by making "required" a mutable field in GtfsTableDescriptor to support dynamic configuration.  Additionally, this PR consolidates some duplicate "isRequired" methods from GtfsTableContainer to make GtfsTableDescriptor the sole source of this info.
=> feat: Make GtfsTableDescriptor.required a mutable property

.github/workflows/stg_web_client_merge.yml, .github/workflows/stg_web_svc_merge.yml, web/client/.gitignore, web/client/src/routes/+page.svelte, web/pipeline/prd.env, web/pipeline/stg.env, web/service/gradle.properties, web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/util/StorageHelper.java, web/service/src/test/java/org/mobilitydata/gtfsvalidator/web/service/util/StorageHelperTest.java
**Summary:**
Adds features required to deploy the web application to a staging environment.
=> feat: deploy web app to staging environment

.github/workflows/acceptance_test.yml, .github/workflows/docker.yml, .github/workflows/end_to_end.yml
GitHub has deprecated set-output and will eventually make it unusable, so this is a preventative fix. See more info here: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Fix for deprecated of `set-output` in GH actions

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/FeedContactValidator.java
`csvRowNumber` is used in every other notice for referencing the csv row number.  This schema change is safe since we haven't published a new release with this change yet.  This PR also swaps the comment for `MissingFeedContactEmailAndUrlNotice` since it seems more appropriate for a documentation string than the existing comment.  Finally, slightly tweak logic in FeedContactValidator.
=> fix: Use csvRowNumber in MissingFeedContactEmailAndUrlNotice for consistency with other notices 

core/src/main/java/org/mobilitydata/gtfsvalidator/table/AnyTableLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultValidatorProvider.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorProvider.java, core/src/test/java/org/mobilitydata/gtfsvalidator/table/AnyTableLoaderTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/table/GtfsFeedLoaderTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsTestMultiFileValidator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsTestSingleFileValidator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsTestTableContainer2.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsTestTableDescriptor2.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/DefaultValidatorProviderTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoaderTest.java, main/src/main/java/org/mobilitydata/gtfsvalidator/runner/ValidationRunner.java
**Summary:**
Closes #1537 
My solution goes thru both SingleEntityValidators and SingleFileValidators, gathers validators that have dependencies with parsing errors. From my perspectives, we should decouple this problem into two parts. First, get the list of validators that couldn't run due to parsing errors. Second, a new logic could be added into the gtfs-validator - if we don't have this and that text files, then validator A B C should not run. @emmambd I request all dev team for code review. Let me know your opinion on the idea of decoupling this issue.
You will see the following info printing out if there's validators that couldn't run due to parsing errors
------------------------------------------------------------------------- 
|   Some validators were …
=> feat: 1537 get list of validators that couldnt run because of a parsing problem

.github/workflows/create_issue_if_referencemd_changes.yml
Upped the version of actions/setup-node to v3.8.1 to use node 16. Following warning from GH:
```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/setup-node@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
=> Updated actions/setup-node action to v3.8.1 to use node 16

.github/workflows/acceptance_test.yml
acceptance_test.yml did not run properly.
It seems the replacement for ::set-output (i.e. >> $GITHUB_OUTPUT) does not accept newlines in the data.
This was a problem with multi-line commit messages.
Just replaced newlines by spaces.
=> Corrected a problem with the acceptance test action.

main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/NoticeView.java, main/src/main/resources/report.html
initialize tooltip in report.html
return non-empty string when getting comment for field in NoticeView
**Summary:**
Closes #1561 
=> bug: initialized tooltip in the report.html

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TripAndShapeDistanceValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/NoticeFieldsTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TripAndShapeDistanceValidatorTest.java
**Summary:**
Created `trip_distance_exceeds_shape_distance`notice when the max value `shapeDistTraveled` of a trip is greater than the max value of `shapeDistTraveled`for its associated shape. 
Closes #163 
=> feat: trip vs shape distance validation

scripts/mobility-database-harvester/harvest_latest_versions.py
**Summary:**
Closes #1587
Removed de-unknown-ulmer-eisenbahnfreunde-gtfs-1081 from the list of files used in the PR validation.
This file has over 40M shapes entries and it's just too big for the changes in https://github.com/MobilityData/gtfs-validator/pull/1553
The acceptance tests pass.
=> Fix: Removed a dataset that is too big from the list used in PR acceptance test

app/gui/src/main/java/org/mobilitydata/gtfsvalidator/app/gui/Main.java, cli/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java, main/src/main/java/org/mobilitydata/gtfsvalidator/runner/ApplicationType.java, main/src/main/java/org/mobilitydata/gtfsvalidator/util/VersionResolver.java, main/src/test/java/org/mobilitydata/gtfsvalidator/util/VersionResolverTest.java, web/service/src/main/java/org/mobilitydata/gtfsvalidator/web/service/Main.java
Per discussion in #1520, we'd like to pull the current release version of the app from the new /version endpoint.
=> feat: Resolve release version from new /version endpoint.

core/src/main/java/org/mobilitydata/gtfsvalidator/validator/DefaultValidatorProvider.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidationContext.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoader.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/ValidationContextTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoaderTest.java
ValidationContext is used to inject params to constructors of *Validator classes. ValidationContext initially supported only CountryCode and CurrentDateTime, e.g.:
@Inject
ExpiredCalendarValidator(
CurrentDateTime currentDateTime, // Injected from ValidationContext
GtfsCalendarTableContainer calendarTable,
GtfsCalendarDateTableContainer calendarDateTable) {...}
This change allows the user to inject any types required for custom validation logic.
=> feat: Support injection of arbitrary types via ValidationContext

.github/workflows/create_issue_if_referencemd_changes.yml
Added label "status: needs triage" to newly created issues with the script, as requested here: https://github.com/MobilityData/gtfs-validator/issues/1080#issuecomment-1826364054
=> fix: Add label to step that creates an issue

web/client/.gitignore, web/client/cypress/e2e/error_messages.cy.js
**Summary:**
Summarize the changes in the pull request, including how it relates to any issues (include the #number, or link them).
Cypress integration tests are failing due to changes in the page structure in the latest release. This PR fixes the test, updating it with the latest expected web structure. 
- Executes Cypress against a local server
Part of #1616
=> fix: cypress error scenario on downloading rules definitions file

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/MixedCaseRecommendedFieldNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ExpiredCalendarValidator.java, web/client/src/routes/rules.html/SectionRefLink.svelte
**Summary:**
Dataset Publishing Guidelines and All Files Recommendations were moved from the best practices section of the spec to the reference file, and as referenced in #1601. This PR updates the links to the References sections of the corresponding rules so no links break.
[mixed_case_recommended_field](https://gtfs-validator.mobilitydata.org/rules.html#mixed_case_recommended_field-rule)
[expired_calendar](https://gtfs-validator.mobilitydata.org/rules.html#expired_calendar-rule) 
both link to https://gtfs.org/schedule/reference/.
=> feat: Update references to Dataset Publishing Guidelines from #1601 

docs/RELEASE.md
**Summary:**
This PR updates the steps in RELEASE.md so generating an analytics report is done after the pre-release. This way, the analytics can be a final QA step before the release is published, rather than informing us of problems after the fact. 
Generating analytics report is added as a release step, after pre-release but before publishing the release.
=> Update release process so we run analytics before release is launched

main/src/main/resources/report.html
**Summary:**
Resolves issue #1608 and duplicate issue #1626.
Links are currently broken. They go to the right web page but not to the individual rule on the page. This corrects the links, which just need "-rule" added to them.
The generated report.html file should have a correct link for each rule it lists, going directly to that rule's section of the documentation.
I tested on a sample report and confirmed the new links work.
- [X ] Run the unit tests with `gradle test` to make sure you didn't break anything
- [X ] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/). …
=> fix: Correct links to rule documentation by adding -rule

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimeIncreasingDistanceValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/NoticeFieldsTest.java
**Summary:**
decreasing_or_equal_stop_time_distance includes prevShapeDistTraveled, not prevStopTimeDistTraveled
Closes #1556  
The name of the field in the report in now replaced from `prevStopTimeDistTraveled` to `prevShapeDistTraveled` in the report. 
Note: the logic was already implemented - it was `prevShapeDistTraveled` that was in the report but under the name `prevStopTimeDistTraveled`.
Using [this feed](https://storage.googleapis.com/storage/v1/b/mdb-latest/o/us-oregon-benton-area-transportation-gtfs-126.zip?alt=media), we get:
=> fix: decreasing_or_equal_stop_time_distance includes prevShapeDistTraveled

core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsInput.java, core/src/test/java/org/mobilitydata/gtfsvalidator/input/GtfsInputTest.java, main/src/main/java/org/mobilitydata/gtfsvalidator/runner/ValidationRunner.java, main/src/test/java/org/mobilitydata/gtfsvalidator/runner/ValidationRunnerTest.java
**Summary:**
When using the feed URL https://www.maricopa-az.gov/home/showpublisheddocument/6491/638307291320330000, it generates an "Error authorizing upload." While verifying the `invalid_input_files_in_subfolder` notice, an additional request is sent to the producer's URL, causing unexpected behaviors (5XX HTTP code).  This PR reuses the response already loaded in memory, avoiding unnecessary external calls and removing the root cause of the original issue. 
As part of this PR, the GTFS validator is sending the _"User-Agent"_ header with the value _"User-Agent: MobilityData GTFS-Validator/4.2.1 (Java 17.0.6)"_
Fixes #1632 
Closes #1562
How to reproduce the bug:
1. Run the validator locally
2. Input https://www.maricopa-az.gov/home/showpublisheddocument/6491/638307291320330000"
3. …
=> fix: Feed generates error to authorize upload

core/src/main/java/org/mobilitydata/gtfsvalidator/input/DateForValidation.java, core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsInput.java, core/src/main/java/org/mobilitydata/gtfsvalidator/testing/LoadingHelper.java, core/src/main/java/org/mobilitydata/gtfsvalidator/validator/ValidationContext.java, core/src/test/java/org/mobilitydata/gtfsvalidator/TestUtils.java, core/src/test/java/org/mobilitydata/gtfsvalidator/input/DateForValidationTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/input/GtfsInputTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsTestEntityValidator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/GtfsTestSingleFileValidator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/testgtfs/WholeFeedValidator.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/ValidationContextTest.java, core/src/test/java/org/mobilitydata/gtfsvalidator/validator/ValidatorLoaderTest.java, main/src/main/java/org/mobilitydata/gtfsvalidator/runner/ValidationRunner.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/DateTripsValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ExpiredCalendarValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/FeedExpirationDateValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadataTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/runner/ValidationRunnerTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/DateTripsValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/ExpiredCalendarValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/FeedExpirationDateValidatorTest.java
**Summary:**
Preparation to make PR #1628 for issue #1292 clearer.
Several rules compare dates in the feed to a reference date, which is usually today. The object that stores the date is called CurrentDateTime and it wraps a ZonedDateTime object. But only the date is ever used (not the time), and the date can be overridden in tests to use specific dates other than today.
This refactor renames the object DateForValidation and wraps a LocalDate object instead. This simplifies the code in several places and will allow PR #1628 to be clearer.
No change in behavior. Internally a LocalDate will be used instead of a ZonedDateTime.
- [X ] Run the unit tests with `gradle test` to make …
=> refactor: Replace CurrentDateTime with DateForValidation and use LocalDate

main/src/main/java/org/mobilitydata/gtfsvalidator/util/VersionResolver.java
**Summary:**
closes #1606 
The version in the html report was `null` with the desktop version of the validator.
It should be the current version.
=> fix: Corrected a problem where the version was null in the desktop version.

main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java, main/src/test/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadataTest.java
**Summary:**
Part 2 of #1640
Remove route name and agency information from GTFS components
=> feat: removed route name and agency information components

.github/workflows/acceptance_test.yml, .github/workflows/end_to_end.yml
**Summary:**
GitRunners are closing up shop, we need to revert back to the built-in runners offered by GitHub.
Email received from GitRunners on Feb 2, 2024:
```
Hello everyone,
This is a sad mail to write for me but it is actually better to face
reality and go on.
It has been one year we launched GitRunners and many things have
happened during this time, unfortunately none of them were good enough
to keep the service continuing operating.
We have tried hard since the start to acquire customers but we
struggled finding a key to convince people to switch to our service:
cost is not a major reason to switch for many companies and apparently
neither is faster hardware. The current growth rate is too low and it
is hard to justify focusing on the product to improve the service and
provide more …
```
=> Fix: replace GitRunners with GitHub's own runners

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/RouteNameValidator.java
=> fix: reformatted doc using HTML table format

.github/workflows/package_installers.yml
**Summary:**
Closes #1674 
CLI jar is now part of the artifacts in the `Package Installers` github action. The name is `gtfs-validator-cli-[commit short hash]`
[Working example](https://github.com/MobilityData/gtfs-validator/actions/runs/8070569966#artifacts)
=> feat: generated CLI package installer

scripts/queue_runner.sh
**Summary:**
After #1683, master build jar supports _--skip_validator_update_ parameter. This PR adds the parameter to the master build jar execution for acceptance tests and end-to-end tests.
Completes #1668.  
Acceptance tests and end-to-end test skips versions checks.
=> chore: add skip version check to the master build

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/DuplicateRouteNameValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimeTravelSpeedValidator.java
**Summary:**
Closes #1672 
Tables in Markdown format do not properly render for notices `fast_travel_between_consecutive_stops` and `duplicate_route_name`. To address the issue I simply used HTML formatting like it was done for the `route_long_name_contains_short_name` notice.
- For `fast_travel_between_consecutive_stops`:
- For `duplicate_route_name`:
=> fix: table not properly rendered in notices

main/src/main/java/org/mobilitydata/gtfsvalidator/report/JsonReportSummary.java, main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java, main/src/main/resources/report.html, main/src/test/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadataTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/report/model/JsonReportSummaryTest.java
**Summary:**
Closes #1685 
Modification to the "GTFS Components" label and replace it with "GTFS Features" so it's harmonized across the Mobility Database and gtfs.org
- HTML Report
- [JSON report example](https://github.com/MobilityData/gtfs-validator/files/14527132/report.json)
=> feat: replace GTFS Components language to GTFS features

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ShapeIncreasingDistanceValidator.java, output-comparator/src/main/java/org/mobilitydata/gtfsvalidator/outputcomparator/cli/ValidationReportComparator.java
**Summary:**
Closes #1638 
Closes #1678 
Concerns have been raised about the `equal_shape_dist_diff_coordinates` error's sensitivity to minor coordinate discrepancies. [Historical discussions](https://github.com/MobilityData/gtfs-validator/pull/1675#issuecomment-1951619648) proposed a $1.11 m$ threshold to distinguish between `ERROR` ($\ge 1.11m$) and `WARNING` ($\lt 1.11 m$) levels. Given the expansion of the Mobility Database since these initial discussions, reevaluating this threshold with current data offers a chance to refine the rule's sensitivity.
- Introduces a 1.11m threshold for `equal_shape_distance_diff_coordinates`, triggering an `ERROR` for distances $\geq 1.11m$.
- Creates a new notice, `equal_shape_distance_diff_coordinates_below_threshold`, with …
=> feat: threshold of 1.11m on `equal_shape_distance_diff_coordinates`

main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/ReportSummary.java, model/src/main/java/org/mobilitydata/gtfsvalidator/notice/SeverityLevel.java, web/client/src/routes/rules.html/+page.svelte
**Summary:**
Closes #1605 
`ERROR` notices are displayed first, followed by `WARNING` and then `INFO` in both the documentation and validation report.
=> feat: display ERRORS first on validator documentation

main/src/main/java/org/mobilitydata/gtfsvalidator/runner/ValidationRunner.java, main/src/main/java/org/mobilitydata/gtfsvalidator/util/VersionInfo.java, main/src/main/java/org/mobilitydata/gtfsvalidator/util/VersionResolver.java
**Summary:**
Closes #1707 
If there is no timeout on the version endpoint, this PR changes nothing.
Changed the code so it does not generate an exception when the version endpoint is called but times out.
Another problem was that the current version (obtained from the jar files) was discarded if there was a time out calling the version endpoint. 
Web validator does not hang forever if there is a timeout while calling the version endpoint.
If the timeout happens, the version is still correct in report.html
** Testing tips **
The timeout is intermittent, and probably only occurs when the validator service is brought up.
To test this, you could add a delay in  [VersionResolver.java](https://github.com/MobilityData/gtfs-validator/blob/dee5802afc2f0e37b0299a5d6dca192c08e …
=> fix: 1707 web validator waits for validation forever

.github/workflows/stg_web_client_merge.yml, web/client/src/routes/+page.svelte
Hotfix for a bug detected for the web validator. The `jobId` was not properly used in the report endpoint.
=> hotfix: jobId incorrectly set in the UI

.github/workflows/notice_migration_generation.yml, .github/workflows/package_installers.yml, docs/RELEASE.md
**Summary:**
Closes #1719 
This issue has 2 parts:
* Include automated Github action of Notice Migration updates when the release is official
The new process is:
1. Manually run the notice migration GH action (manually specifying the version) -> this adds to the NOTICE_MIGRATION.md file and creates the PR
2. Merge the PR
3. Release
- Upload the .zip installers to the release assets.
Follow the new section `2. Update NOTICE_MIGRATION.md file` in docs/RELEASE.md. 
After running the github action, a new PR should have been created with the notice migration data for the specified release.
For the upload zip installers task , create a fake draft release and verify that the 3 installer zip files are present as release artefacts.
Please make sure these boxes are checked …
=> feat: Changed notice migration generation. Added zip file to release.

.github/workflows/stg_web_svc_merge.yml, .github/workflows/web_release.yml
**Summary:**
This PR addresses part of issue #1746. It sends a repository dispatch notification to the [mobility-feed-api](https://github.com/MobilityData/mobility-feed-api) with a type of either `gtfs-validator-update-stg` or `gtfs-validator-release` whenever the GTFS Web Validator services are updated.
**Expected Behavior:**
- On merging to the `master` branch, the staging web services are updated, triggering a `gtfs-validator-update-stg` notification.
- On release, the production services are updated, triggering a `gtfs-validator-release` notification.
=> feat: notify mobility-feeds-api when the web validator is updated

main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsTransferSchema.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TransferStopIdsConditionalValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/TransferStopIdsConditionalValidatorTest.java
**Summary:**
This PR aligns the validator response with the specification on the transfers.txt from and to stop IDs. The specification marks these fields as required for all records except those with a transfer_type of 4 or 5.
Closes #1621 
For transfers.txt records with transfer types 4 and 5(in seat transfer types), the missing required field is not triggered.
=> fix: set transfer from and to stop ids as conditional required fields

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/MissingTripEdgeValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/MissingTripEdgeValidatorTest.java
**Summary:**
This update modifies the `missing_trip_edge` notice to ensure it is not triggered if the `GtfsStopTime` entity has *either* the `startPickupDropOffWindow` or `endPickupDropOffWindow` column defined.
**Expected Behavior:**  
The `missing_trip_edge` notice will no longer be triggered in cases where one of the above columns is present. For example, using [this dataset](https://data.trilliumtransit.com/gtfs/islandtransit-wa-us/islandtransit-wa-us--flex-v2-TEST.zip), the notice is no longer triggered, as shown below:
=> feat: update `missing_trip_edge` for flex feed

main/src/main/resources/report.html
**Summary:**
Closes #1854 
only display service window on HTML report, not start/end date
=> fix: only display service window on HTML report, not start/end date

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/BookingRulesEntityValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/BookingRulesEntityValidatorTest.java
**Summary**
This PR introduces a new validation rule that triggers an `ERROR` severity notice when the following conditions are met:
- `booking_type = 1` (Same-day booking)
- Any of the following fields are present in the booking rule:
- `prior_notice_last_day`
- `prior_notice_last_time`
- `prior_notice_start_time`
- `prior_notice_service_id`
**Expected Behavior**
A validation notice will be generated if the conditions listed above are met, flagging the presence of restricted fields in a same-day booking rule.
Example using [this test dataset](https://github.com/user-attachments/files/17131804/Archive.zip).
=> feat: flex - added `forbidden_same_day_booking_field_value` notice

main/src/main/java/org/mobilitydata/gtfsvalidator/report/JsonReportSummary.java, main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeatureMetadata.java, main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java, main/src/main/resources/report.html, main/src/test/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadataTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/report/model/JsonReportSummaryTest.java
**Summary:**
- Updated features based on the [table description](https://github.com/MobilityData/gtfs-validator/issues/1679#issuecomment-2332601261)
- Added documentation links to the HTML report for each feature
**Expected Behavior:**
- Ensures consistent naming conventions between the HTML report and the official documentation.
- Each feature listed in the report now includes a clickable link that directs users to the corresponding section in the official documentation
=> feat: changes + added documentation to features

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/BookingRulesEntityValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/BookingRulesEntityValidatorTest.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/NoticeFieldsTest.java
**Summary:**
This PR introduces three new validation notices: `forbidden_prior_day_booking_field_value`, `invalid_prior_notice_duration_min`, and `forbidden_prior_notice_start_day`.
- **forbidden_prior_day_booking_field_value**:
- **Error Logic**: 
- Trigger when `booking_type = 2` and either `prior_notice_duration_min` or `prior_notice_duration_max` is present.
- **invalid_prior_notice_duration_min**:
- **Error Logic**: 
- Trigger when `prior_notice_duration_min` is greater than `prior_notice_duration_max`.
- **forbidden_prior_notice_start_day**:
- **Error Logic**: 
- Trigger when `prior_notice_start_day` is defined and `prior_notice_duration_max` is also defined.
**Expected Behavior:**
A validation notice with ERROR severity is generated when any of the above conditions are met for each …
=> feat: added `forbidden_prior_day_booking_field_value`, `invalid_prior_notice_duration_min` and `forbidden_prior_notice_start_day` notices

main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsStopSchema.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/MissingStopsFileValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/MissingStopsFileValidatorTest.java
**Summary:**
Modifies `stops.txt` to be conditionally required.
Logic: If `stops.txt` doesn't exist, only trigger a `missing_required_file` notice if `locations.geojson` also doesn't exist.
=> feat: modify `stops.txt` to be conditionally required

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ShapeToStopMatchingValidator.java
**Summary:**
Closes #1881 
modified stop_too_far_from_shape so it only checks stop times records that have a stop_id. It should ignore stop times that don't have a stop_id.
Before:
After:
=> feat: modified stop_too_far_from_shape so it only checks stop times record with a stop_id

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ShapeIncreasingDistanceValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TripAndShapeDistanceValidator.java
**Summary:**
We received some user feedback that the `trip_distance_exceeds_shape_distance_below_threshold` and `equal_shape_distance_diff_coordinates_below_threshold` notice language was confusing. Added description about the value being greater than 0 but below the threshold to more clearly convey this.
- [X ] Run the unit tests with `gradle test` to make sure you didn't break anything
=> docs: Clarified below threshold language in notices

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/ForbiddenGeographyIdNotice.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimeIncreasingDistanceValidator.java, main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopTimesShapeDistTraveledPresenceValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StopTimesShapeDistTraveledPresenceValidatorTest.java
**Summary:**
Closes #1885 
Added a validator that checks for stopTime entries with location_id or location_group_id values that also have shape_dist_traveled value. If found, add a ForbiddenShapeDistTraveledNotice notice.
Used http://data.trilliumtransit.com/gtfs/thurston-wa-us/thurston-wa-us--flex-v2.zip as a test dataset.
Report before the change:
---
Report after the change:
***
Essentially we created 156 forbidden_shape_dist_traveled notices.
https://github.com/MobilityData/gtfs-validator/pull/1895 should take care of removing the 156 decreasing_or_equal_stop_time_distance notices.
=> feat: Added a validator for forbidden shape_distance

scripts/mobility-database-harvester/harvest_latest_versions.py
**Summary:**
Currently, the number of concurrent jobs is limited by the type of account the organization is holding. As a Team account, we have 60 maximum number of jobs that can concurrently be executed at a time. Having 256 rows in the acceptance tests has two main issues. The first only 60 can be executed concurrently so having more than 60 will make the agents wait and don't add any value as a concurrent job. Secondly, the billable time is computed per second, but the minimum billable time is one minute; all the jobs completed before one minute will be charged one minute, `loosing` few seconds per small job.
Acceptance tests passes and the resources are more efficient used.
=> ci: aling matrix dimensions to max concurrent jobs

.github/actions/extract-1password-secret/action.yml, .github/workflows/publish_assets.yml, .github/workflows/stg_web_svc_merge.yml, .github/workflows/web_release.yml, build.gradle
Closes #1906 
**Summary:**
Set the proper 1password secret references that were changed at one point making the publication to Sonatype fail.
Added the use of a github repo variable `ONE_PASSWORD_SECRET_REFERENCES` containing key-value pairs for the secret references:
```
SONATYPE_TOKEN_USERNAME = op://rbiv7rvkkrsdlpcrz3bmv7nmcu/Sonatype user token/username
SONATYPE_TOKEN_PASSWORD = op://rbiv7rvkkrsdlpcrz3bmv7nmcu/Sonatype user token/password
MAVEN_GPG_PRIVATE_KEY = op://rbiv7rvkkrsdlpcrz3bmv7nmcu/dkkfywvsr3xq6eyeubq6cldaxi/Private Key
MAVEN_GPG_PASSPHRASE = op://rbiv7rvkkrsdlpcrz3bmv7nmcu/dkkfywvsr3xq6eyeubq6cldaxi/password
GITHUB_GENERIC_ACTION_CREDENTIALS = op://rbiv7rvkkrsdlpcrz3bmv7nmcu/GitHub generic action token for all repos/credential
```
The secret references in this variable …
=> feat: Use a github variable containing 1password secret references

.github/workflows/docker.yml, .github/workflows/end_to_end.yml, .github/workflows/notice_migration_generation.yml, .github/workflows/test_pack_doc.yml
**Summary:**
This pull request updates various GitHub Actions workflows to use the latest version of the `actions/upload-artifact` and `actions/download-artifact` actions.
=> chore: artifact action v3 upgrade

.github/workflows/acceptance_test.yml, .github/workflows/end_to_end.yml
**Summary:**
Missed from previous #1926 work. 
**Out of scope**
Leaving out of scope the fix of Python scripts running in ubuntu-latest. This will be solved in #1938
The upload artifact is upgraded to v4, and the E2E test passed. Successfully build [link](https://github.com/MobilityData/gtfs-validator/actions/runs/12678281679).
=> chore: upgrade missed e2e upload artifact to v4

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ParentStationValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/ParentStationValidatorTest.java
**Summary:**
See title. As per #1604, "unused_parent_station" is a bit of a misnomer because a station without any stops is not, by definition, a parent station.
Closes #1604
The "unused_parent_station" rule is now called "unused_station", including in [rules.html](https://gtfs-validator.mobilitydata.org/rules.html).
**Testing:**
Three tests are failing when I run `gradle test` but they fail on the master branch as well:
- JsonReportSummaryTest.withFeedMetadataNoConfigTest
- JsonReportSummaryTest.withFeedMetadataWithConfigTest
- VersionResolverTest.classMethod
=> feat: rename unused_parent_station rule to unused_station

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/ExpiredCalendarValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/ExpiredCalendarValidatorTest.java
**Summary:**
This PR updates the validator for the expired_calendar rule to sort notices by row number.
Closes #1931 
expired_calendar notices are sorted by row number in ascending order.
**Testing:**
I used the first sample file in #1931 and validated with and without my changes.
Before:
csvRowNumber | serviceId
-- | --
113 | "66"
137 | "67"
199 | "68"
41 | "27"
42 | "28"
43 | "29"
... | ...
After:
csvRowNumber | serviceId
-- | --
2 | "36"
3 | "37"
4 | "38"
5 | "39"
6 | "40"
7 | "34"
... | ...
=> fix: sort expired_calendar notices by row number

core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsInput.java
**Summary:**
This PR fixes a bug with our logic to check whether a ZIP file we're loading has GTFS files in a subfolder. It looks like `ZipInputStream.getNextEntry` doesn't always return subfolders, depending on how the ZIP file was created. The subfolder and ZIP file having the same name in #1912 was a red herring.
<details>
```
$ unzip -l piercetransit-wa-us--flex-v2.zip
Archive:  piercetransit-wa-us--flex-v2.zip
Length      Date    Time    Name
---------  ---------- -----   ----
170  11-28-2023 15:22   piercetransit-wa-us--flex-v2/timetables.txt
81  11-28-2023 15:22   piercetransit-wa-us--flex-v2/fare_attributes.txt
18  11-28-2023 15:22   piercetransit-wa-us--flex-v2/stop_attributes.txt
56  11-28-2023 15:22   piercetransit-wa-us--flex-v2/transfers.txt
183  11-28-2023 15:22 …
```
=> fix: fix logic to check for nested GTFS files in ZIP

.github/workflows/package_installers.yml, .github/workflows/publish_assets.yml, README.md, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/NoticeFieldsTest.java
**Summary:**
This pull request includes changes to the GitHub workflows to support the packaging and publishing of both CLI and GUI JAR assets.
Closes #1999 
The GTFS-Validator GUI can be downloaded and executed from the project assets as a single JAR.
=> feat: publish the Java GUI as a independent jar asset

core/src/main/java/org/mobilitydata/gtfsvalidator/notice/MissingPriorNoticeLastDayNotice.java, core/src/main/java/org/mobilitydata/gtfsvalidator/notice/MissingPriorNoticeLastTimeNotice.java
**Summary:**
Follow-up to [PR comment](https://github.com/MobilityData/gtfs-validator/pull/1996#pullrequestreview-2655380934). 
Related to #1977
The description of MissingPriorNoticeLastDayNotice and MissingPriorNoticeLastTimeNotice is updated as suggested
=> fix: update MissingPriorNoticeLastDayNotice and MissingPriorNoticeLastTimeNotice documentation

main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PickupBookingRuleIdValidator.java, main/src/test/java/org/mobilitydata/gtfsvalidator/validator/PickupBookingRuleIdValidatorTest.java
**Summary:**
Closes #1821 
I've checked some feeds listed in the New Warnings https://github.com/MobilityData/gtfs-validator/pull/1966 in this PR, for instance, ca-quebec-exo-laurentides-gtfs-744, the dataset doesn't have a booking rules file and  its report doesn't contain MissingPickupDropOffBookingRuleIdNotice. https://mobilitydatabase.org/feeds/gtfs/mdb-744
=> feat: modified MissingPickupDropOffBookingRuleIdNotice logic

core/src/main/java/org/mobilitydata/gtfsvalidator/input/GtfsZipFileInput.java, core/src/main/java/org/mobilitydata/gtfsvalidator/reportsummary/AgencyMetadata.java, main/src/main/java/org/mobilitydata/gtfsvalidator/reportsummary/model/FeedMetadata.java, main/src/main/resources/report.html
**Summary:**
This PR standardizes the empty strings by populating the values with `""` instead of `N/A` in the generated report.json. The `report.html` will still render `"N/A"` for empty values.
Closes #2003 
Empty values are actually empty in the generated `report.json` instead of `"N/A"`.
=> feat: standardize empty value on report.json

main/src/main/resources/report.html
**Summary:**
Closes #2025 
Reinstated the limit of 50 notices listed per notice type in the html report.
The html report should never have more than 50 notices listed per notice type.
For the sake of expediency I did not add a test case for this.
It would be way more involved since it requires parsing the resulting HTML report file.
We can add a separate issue for that.
=> fix: Put back the limit of 50 records per notice type in the html report.
